;/*FB_PKG_DELIM*/

__d("CometGroupAboutRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="28170219579232253"}),null);
__d("CometGroupAboutRootQuery$Parameters",["CometGroupAboutRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometGroupAboutRootQuery_facebookRelayOperation"),metadata:{},name:"CometGroupAboutRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometGroupAboutRoot.entrypoint",["CometGroupAboutRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildGroupCometRootRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildGroupCometRootRoute.entrypoint")(r("JSResourceForInteraction")("CometGroupAboutRoot.react").__setRef("CometGroupAboutRoot.entrypoint"),function(e){var t=e.routeProps,r=t.groupID;return{queries:{aboutQueryReference:{parameters:n("CometGroupAboutRootQuery$Parameters"),variables:{groupID:r,scale:o("WebPixelRatio").get()}}}}});l.default=e}),98);
__d("CometGroupEventsRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27816091738021206"}),null);
__d("CometGroupEventsRootQuery$Parameters",["CometGroupEventsRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometGroupEventsRootQuery_facebookRelayOperation"),metadata:{},name:"CometGroupEventsRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometGroupEventsRoot.entrypoint",["CometGroupEventsRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildGroupCometRootRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=3,s=r("buildGroupCometRootRoute.entrypoint")(r("JSResourceForInteraction")("CometGroupEventsRoot.react").__setRef("CometGroupEventsRoot.entrypoint"),function(t){var r=t.routeProps,a=r.groupID,i={count:e,groupID:a,scale:o("WebPixelRatio").get()};return{queries:{queryReference:{parameters:n("CometGroupEventsRootQuery$Parameters"),variables:i}}}});l.default=s}),98);
__d("GroupsCometCreateRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27148550504773184"}),null);
__d("GroupsCometCreateRootQuery$Parameters",["GroupsCometCreateRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("GroupsCometCreateRootQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometCreateRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("GroupsCometCreateRoot.entrypoint",["GroupsCometCreateRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e,n,a,i,l=t.routeParams,s=t.routeProps;return{queries:{groupCreateRootQueryReference:{parameters:r("GroupsCometCreateRootQuery$Parameters"),variables:{fundraiser_challenge_id:(e=l.fundraiser_challenge_id)!=null?e:"0",fundraiser_challenge_id_is_null:l.fundraiser_challenge_id==null,package_id:(n=l.package_id)!=null?n:"0",parent_group_id:s.parentGroupID,referrer:(a=(i=l.create_ref)==null?void 0:i.toUpperCase())!=null?a:"UNKNOWN_REF",scale:o("WebPixelRatio").get()}}}}},root:r("JSResourceForInteraction")("GroupsCometCreateRoot.react").__setRef("GroupsCometCreateRoot.entrypoint")};l.default=e}),98);
__d("GroupsCometDiscoverContentQuery$Parameters",["GroupsCometDiscoverContentQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("GroupsCometDiscoverContentQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometDiscoverContentQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("GroupsCometDiscoverRoot.entrypoint",["GroupsCometDiscoverContentQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGroupsTabRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=o("buildCometGroupsTabRoute.entrypoint").buildCometGroupsTabRouteEntrypoint(r("JSResourceForInteraction")("GroupsCometDiscoverRoot.react").__setRef("GroupsCometDiscoverRoot.entrypoint"),function(e){return{queries:{discoverQueryReference:{parameters:n("GroupsCometDiscoverContentQuery$Parameters"),variables:{hoisted_group_id:e.routeProps.hoisted_group_id,promotion_theme:e.routeProps.promotion_theme,scale:o("WebPixelRatio").get(),source:e.routeProps.source}}}}});l.default=e}),98);
__d("GroupsCometFilesTabRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="23889300290699369"}),null);
__d("GroupsCometFilesTabRootQuery$Parameters",["GroupsCometFilesTabRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("GroupsCometFilesTabRootQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometFilesTabRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("GroupsCometFilesTabRoot.entrypoint",["GroupsCometFilesTabRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildGroupCometRootRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildGroupCometRootRoute.entrypoint")(r("JSResourceForInteraction")("GroupsCometFilesTabRoot.react").__setRef("GroupsCometFilesTabRoot.entrypoint"),function(e){var t=e.routeProps,r=t.groupID;return{queries:{queryReference:{parameters:n("GroupsCometFilesTabRootQuery$Parameters"),variables:{groupDocsFileName:null,groupID:r,orderby:null,scale:o("WebPixelRatio").get()}}}}});l.default=e}),98);
__d("GroupsCometPhotosRootQueryContainerQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="34206624742316139"}),null);
__d("GroupsCometPhotosRootQueryContainerQuery$Parameters",["GroupsCometPhotosRootQueryContainerQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("GroupsCometPhotosRootQueryContainerQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometPhotosRootQueryContainerQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("GroupsCometPhotosRootQueryVariables",[],(function(t,n,r,o,a,i){"use strict";var e=8;i.count=e}),66);
__d("GroupsCometPhotosRoot.entrypoint",["GroupsCometPhotosRootQueryContainerQuery$Parameters","GroupsCometPhotosRootQueryVariables","JSResourceForInteraction","WebPixelRatio","buildGroupCometRootRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildGroupCometRootRoute.entrypoint")(r("JSResourceForInteraction")("GroupsCometPhotosRoot.react").__setRef("GroupsCometPhotosRoot.entrypoint"),function(e){var t=e.routeProps,r=t.extraSections,a=t.groupID;return{extraProps:{extraSections:r},queries:{queryReference:{parameters:n("GroupsCometPhotosRootQueryContainerQuery$Parameters"),variables:babelHelpers.extends({groupID:a,scale:o("WebPixelRatio").get()},o("GroupsCometPhotosRootQueryVariables"))}}}});l.default=e}),98);
__d("GroupsCometResponsiveColumnsTabRoot.react",["react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t=o("react-compiler-runtime").c(6),n=e.children,r=e.isAdminToolsPageRoot,a=e.testid,i=r===void 0?!1:r,l;t[0]!==i?(l={0:{className:"xamitd3 xieb3on x193iq5w xrljuej x14vqqas"},1:{className:"xamitd3 xieb3on x193iq5w xrljuej x1aody8q x14vqqas"}}[(i===!0)<<0],t[0]=i,t[1]=l):l=t[1];var u;return t[2]!==n||t[3]!==l||t[4]!==a?(u=s.jsx("div",babelHelpers.extends({},l,{"data-testid":void 0,children:n})),t[2]=n,t[3]=l,t[4]=a,t[5]=u):u=t[5],u}l.default=u}),98);