;/*FB_PKG_DELIM*/

__d("BirthdayCometContentQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27545653125096768"}),null);
__d("BirthdayCometContentQuery$Parameters",["BirthdayCometContentQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("BirthdayCometContentQuery_facebookRelayOperation"),metadata:{},name:"BirthdayCometContentQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("EventCometBirthdayMegaphoneRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="36545734135072192"}),null);
__d("EventCometBirthdayMegaphoneRootQuery$Parameters",["EventCometBirthdayMegaphoneRootQuery_facebookRelayOperation","FBReels_enable_view_dubbed_audio_type_gk.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("EventCometBirthdayMegaphoneRootQuery_facebookRelayOperation"),metadata:{},name:"EventCometBirthdayMegaphoneRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__FBReels_enable_view_dubbed_audio_type_gkrelayprovider:n("FBReels_enable_view_dubbed_audio_type_gk.relayprovider")}}};a.exports=e}),null);
__d("EventCometDashboardRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="24097173779970476"}),null);
__d("EventCometDashboardRootQuery$Parameters",["EventCometDashboardRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("EventCometDashboardRootQuery_facebookRelayOperation"),metadata:{},name:"EventCometDashboardRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("buildCometEventDashboardRoute.entrypoint",["EventCometDashboardRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","createContentAreaCompoundEntryPointBuilder","gkx"],(function(t,n,r,o,a,i,l){"use strict";var e=r("createContentAreaCompoundEntryPointBuilder")(r("JSResourceForInteraction")("EventCometDashboardRoot.react").__setRef("buildCometEventDashboardRoute.entrypoint"),function(e){var t=e.routeProps,a=r("gkx")("22809");return{query$key:{parameters:n("EventCometDashboardRootQuery$Parameters"),variables:{isHome:t.is_home===!0,isLoggedOut:a,scale:o("WebPixelRatio").get()}}}});l.default=e}),98);
__d("BirthdayCometEventsRoot.entrypoint",["BirthdayCometContentQuery$Parameters","EventCometBirthdayMegaphoneRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometEventDashboardRoute.entrypoint","qex"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCometEventDashboardRoute.entrypoint")(r("JSResourceForInteraction")("BirthdayCometEventsRoot.react").__setRef("BirthdayCometEventsRoot.entrypoint"),function(e){var t,a=e.routeProps;return{extraProps:a,queries:{birthdays$key:{parameters:n("BirthdayCometContentQuery$Parameters"),variables:{offset_month:-1,scale:o("WebPixelRatio").get(),show_mutual_follower_birthdays:(t=r("qex")._("1317"))!=null?t:!1,stream_birthday_months:!0}},megaphone$key:{parameters:n("EventCometBirthdayMegaphoneRootQuery$Parameters"),variables:{scale:o("WebPixelRatio").get(),surface_nux_id:"11533"}}}}});l.default=e}),98);
__d("EventCometHomeRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="37180102488300066"}),null);
__d("EventCometHomeRootQuery$Parameters",["EventCometHomeRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("EventCometHomeRootQuery_facebookRelayOperation"),metadata:{},name:"EventCometHomeRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("EventDiscoveryTabType.facebook",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum").Mirrored(["ARTS_CULTURE","CAUSES","CUSTOM","FILM","FITNESS","FOLLOWING","FOOD_DRINK","FRIENDS","GROUPS","HEALTH","KID_FRIENDLY","LEARNING_CLASS","LIVE_NOW","LOCAL","MUSIC","NETWORKING","NIGHTLIFE","NOW","ONLINE","POPULAR_NOW","RECOMMENDED","RELIGION","SALE","SHOPPING","THIS_WEEK","THIS_WEEKEND","TODAY","TOP_CATEGORY","TOP_EVENTS","YOU","YOUR_EVENTS","YOUR_SAVED_CONTENT"]),l=e;i.default=l}),66);
__d("EventCometHomeRoot.entrypoint",["EventCometHomeRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometEventDashboardRoute.entrypoint","gkx"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCometEventDashboardRoute.entrypoint")(r("JSResourceForInteraction")("EventCometHomeRoot.react").__setRef("EventCometHomeRoot.entrypoint"),function(e){var t,a,i,l,s,u,c,d,m,p,_,f,g,h,y,C=e.routeProps,b=(t=C.discover_tab)!=null?t:"RECOMMENDED",v=(a=C.date_filter_option)!=null?a:null,S=(i=C.location_id)!=null?i:null,R=(l=C.event_flags)!=null?l:null,L=(s=(u=C.jnb_event_ids)==null?void 0:u.split(","))!=null?s:[],E=r("gkx")("3848"),k=E?L:[],I=(c=window.innerHeight)!=null?c:(d=C.browser_dimension)==null?void 0:d.y,T=(m=window.innerWidth)!=null?m:(p=C.browser_dimension)==null?void 0:p.x,D=2;T>=2296?D=6:T>=1680?D=4:T>=1372&&(D=3);var x=(_=C.start_date)!=null?_:null,$=(f=C.end_date)!=null?f:x,P=x!=null?new Date(x):null,N=$!=null?new Date($):null;N==null||N.setDate(N.getDate()+1);var M=P!=null?P.getTime()/1e3:null,w=N!=null?N.getTime()/1e3:M;return{extraProps:{ISOEndDate:$,ISOStartDate:x,dateFilterOption:v,discoverTab:b,enableHScroll:E,eventFlags:R,locationID:S},queries:{homeEvents$key:{parameters:n("EventCometHomeRootQuery$Parameters"),variables:{JNBEventID1:(g=L[0])!=null?g:"",JNBEventID2:(h=L[1])!=null?h:"",JNBEventID3:(y=L[2])!=null?y:"",discoverTab:b,enableJnbHScroll:E,endTimestamp:w,eventFlags:R,hasJNBEventID:L.length>0,initialCount:D*(I>=768?3:2),jnbHScrollEventIDs:k,locationID:S,scale:o("WebPixelRatio").get(),startTimestamp:M}}}}});l.default=e}),98);
__d("FriendingCometBirthdayRootContentQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26560602460256894"}),null);