(function(g){var window=this;'use strict';var Gq=function(D){D.publish("cardstatechange",D.EP()&&D.Sv()?1:0)},xf=function(D,w){var Q=g.Gx(w),Y=Q?w:arguments;
for(Q=Q?0:1;Q<Y.length;Q++){if(D==null)return;D=D[Y[Q]]}return D},qq$=function(D){var w=g.si(D);
D=g.D9(D);return new g.KG(w.x,w.y,D.width,D.height)},dJi=function(D,w,Q){var Y;
return Y=g.jy(D,w,function(){g.zz(Y);Q.apply(D,arguments)},{})},Fr=function(D){D=g.CP(D);
delete RB[D];g.rV(RB)&&oB&&oB.stop()},N3A=function(){oB||(oB=new g.U5(function(){its()},20));
var D=oB;D.isActive()||D.start()},its=function(){var D=g.N8();
g.oA(RB,function(w){T3y(w,D)});
g.rV(RB)||N3A()},CQ=function(D,w,Q,Y){g.m4.call(this);
if(!Array.isArray(D)||!Array.isArray(w))throw Error("Start and end parameters must be arrays");if(D.length!=w.length)throw Error("Start and end points must be the same length");this.S=D;this.N=w;this.duration=Q;this.G=Y;this.coords=[];this.progress=this.C=0;this.j=null},T3y=function(D,w){w<D.startTime&&(D.endTime=w+D.endTime-D.startTime,D.startTime=w);
D.progress=(w-D.startTime)/(D.endTime-D.startTime);D.progress>1&&(D.progress=1);D.C=1E3/(w-D.j);D.j=w;IIm(D,D.progress);D.progress==1?(D.Y=0,Fr(D),D.onFinish(),D.Vv()):D.isPlaying()&&D.EV()},IIm=function(D,w){typeof D.G==="function"&&(w=D.G(w));
D.coords=Array(D.S.length);for(let Q=0;Q<D.S.length;Q++)D.coords[Q]=(D.N[Q]-D.S[Q])*w+D.S[Q]},KZu=function(D,w){g.fK.call(this,D);
this.coords=w.coords;this.x=w.coords[0];this.y=w.coords[1];this.z=w.coords[2];this.duration=w.duration;this.progress=w.progress;this.fps=w.C;this.state=w.Y},uL=function(D,w,Q,Y,t){CQ.call(this,w,Q,Y,t);
this.element=D},qp=function(D,w,Q,Y,t){if(w.length!=2||Q.length!=2)throw Error("Start and end points must be 2D");
uL.call(this,D,w,Q,Y,t)},Pji=function(D){return Math.pow(D,3)},UJM=function(D){return 3*D*D-2*D*D*D},dW=function(D){return D.baseUrl||null},iL=function(D,w){return g.bx(g.EU(D,w),Q=>!!Q)},cQy=function(D,w,Q){function Y(oh){var H7=oh.hovercardButton;
if(!H7)return null;H7=H7.subscribeButtonRenderer;if(!H7)return null;var ZP=O(H7.unsubscribedButtonText),W0=O(H7.subscribedButtonText);if(H7.subscribed){var ix=O(H7.subscriberCountWithUnsubscribeText);var c$=O(H7.subscriberCountText)}else ix=O(H7.subscriberCountText),c$=O(H7.subscriberCountWithSubscribeText);var J4=null;return oh.signinEndpoint&&((J4=xf(oh,"signinEndpoint","webNavigationEndpointData","url"))||(J4=g.H(H7.signInEndpoint?.commandMetadata,g.MX)?.url),!J4)?null:ZP&&(W0||J4)?{subscribed:H7.subscribed,
subscribeText:ZP,subscribeCount:ix,unsubscribeText:W0,unsubscribeCount:c$,enabled:H7.enabled,signinUrl:J4,classic:oh.useClassicSubscribeButton}:null}
function t(oh){if(oh){var H7=[],ZP=oh.videoId;ZP&&H7.push("v="+ZP);(ZP=oh.playlistId)&&H7.push("list="+ZP);(oh=oh.startTimeSeconds)&&H7.push("t="+oh);return"/watch?"+H7.join("&")}}
function O(oh){if(!oh)return null;var H7=oh.simpleText;return H7?H7:oh.runs?g.EU(oh.runs,ZP=>ZP.text).join(""):null}
w=w.endscreenElementRenderer;if(!w)return null;var n=w.style,X=w.endpoint||{},W=null,v=null,V=!1,y=null,J=null,M=null,R=null,I=!1,c=null,h=null,L=null,b=null,A=null,Qi=null;if(n==="VIDEO")g.H(X,g.dQ)?W=g.H(X,g.dQ).url:(Qi=g.H(X,g.OZ),W=t(Qi)),v=!1,y=D,w.thumbnailOverlays?(V=w.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,J=O(V.text),V=V.style==="LIVE"):J=O(w.videoDuration);else if(n==="PLAYLIST")g.H(X,g.dQ)?W=g.H(X,g.dQ).url:(Qi=g.H(X,g.OZ),W=t(Qi)),v=!1,y=D,M=O(w.playlistLength);else if(n===
"CHANNEL"){if(I=xf(X,"browseEndpoint","browseId"))R=I,W=`/channel/${R}`;v=!1;y="new";(I=!!w.isSubscribe)?c=Y(w):h=O(w.subscribersText)}else n==="WEBSITE"?((L=xf(X,"urlEndpoint","url"))&&(W=L),v=!0,y="new",L=w.icon.thumbnails[0].url):n==="CREATOR_MERCHANDISE"&&(w.productPrice&&(b=O(w.productPrice)),w.additionalFeesText&&(A=O(w.additionalFeesText)),(v=xf(X,"urlEndpoint","url"))&&(W=v),v=!0,y="new");D=xf(w,"title","accessibility","accessibilityData","label");var ah=w.endpoint?w.endpoint.clickTrackingParams:
null,Fx="";if(w.metadata){let oh=O(w.metadata);oh&&(Fx=oh)}return{id:`element-${Q}`,type:n,title:O(w.title),metadata:Fx,callToAction:O(w.callToAction),RV:w.image,iconUrl:L,left:Number(w.left),width:Number(w.width),top:Number(w.top),aspectRatio:Number(w.aspectRatio),startMs:Math.floor(Number(w.startMs)),endMs:Math.floor(Number(w.endMs)),videoDuration:J,Mi:V,playlistLength:M,channelId:R,subscribeButton:c,subscribersText:h,isSubscribe:I,targetUrl:W||null,IQ:v,sessionData:ah?{itct:ah}:null,Xy:y,sa:D?
D:null,isPlaceholder:w.isPlaceholder,impressionUrls:iL(w.impressionUrls||[],dW),e2:iL(w.hovercardShowUrls||[],dW),clickUrls:iL(X.loggingUrls||[],dW),visualElement:g.v3(w.trackingParams),productPrice:b,additionalFeesText:A,watchEndpoint:Qi||null}},Np=function(D,w){var Q={startMs:Math.floor(Number(D.startMs)),
impressionUrls:iL(D.impressionUrls||[],dW),elements:iL(D.elements||[],(Y,t)=>cQy(w,Y,t))};
D.trackingParams&&(Q.visualElement=g.v3(D.trackingParams));return Q},Tq=function(D){return D.player.X().playerStyle==="creator-endscreen-editor"},hFy=function(D){return D.player.getVideoData().wx?"current":D.O?"new":"current"},IB=function(D,w,Q=!0){D.player.C2("creatorendscreen");
D.D&&(D.D.dispose(),D.D=null,D.G.dispose(),D.G=null);for(var Y of Object.values(D.S))Y.dispose();D.S={};D.C={};D.V.length>0&&(D.V.forEach(t=>{t.dispose()}),D.V.length=0);
D.Y&&(g.jl(D.Y,"ytp-ce-element-show"),D.Y.setAttribute("aria-hidden","true"));D.N=0;if((D.endscreen=w)&&w.elements){Q&&rQi(D);Q=[];Y=new g.z1(w.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});Q.push(Y);D.player.X().D||(D.D=new g.B({Z:"div",J:"ytp-ce-shadow"}),g.PA(D.player,D.D.element,4),D.G=new g.hN(D.D,200));for(Y=0;Y<w.elements.length;++Y){let t=w.elements[Y],O=LZm(D,t);if(!O){g.ou(new g.Aq("buildEndscreenElement null",t));continue}D.S[t.id]=O;D.C[t.id]=t;g.PA(D.player,
O.element,4);let n=new g.z1(t.startMs,t.endMs,{id:"ytp-ce-element-"+t.id,namespace:"creatorendscreen"});Q.push(n);eFi(D,O,t)}D.player.HK(Q);D.YJ()}},btP=function(D){var w=D.player.getVideoData(),Q=w.videoId;
D.j&&D.j.abort();Q={method:"POST",onFinish:t=>{var O=D.j=null;t.status===200&&(t=t.responseText,t.substring(0,3)===")]}"&&(t=t.substring(3),O=JSON.parse(t),O=Np(O,hFy(D))));IB(D,O)},
urlParams:{v:Q},withCredentials:!0};D.O&&(Q.urlParams.ptype="embedded");var Y=w.WG;Y&&(Q.postParams={ad_tracking:Y});if(w=g.D0C(w))if(w=g.P0(w),w=g.Nv(w))D.j=g.mp(w,Q)},rQi=function(D){var w=g.lt(),Q=g.fu();
Q&&w&&D.endscreen.visualElement&&g.RY(g.Lu)(void 0,Q,w,D.endscreen.visualElement)},LZm=function(D,w){var Q=null;
switch(w.type){case "VIDEO":D={Z:"div",uK:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":w.sa||"","aria-hidden":"true"},K:[{Z:"div",J:"ytp-ce-element-shadow"},{Z:"div",J:"ytp-ce-covering-image",W:KQ(w)},{Z:"div",J:"ytp-ce-covering-shadow-top"},{Z:"a",J:"ytp-ce-covering-overlay",W:{href:PX(D,w.targetUrl),tabindex:"-1"},K:[{Z:"div",uK:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.DM(w.title||"")},YU:w.title},{Z:"div",J:w.Mi?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
YU:w.videoDuration||void 0}]}]};Q=new g.B(D);break;case "PLAYLIST":D={Z:"div",uK:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":w.sa||"","aria-hidden":"true"},K:[{Z:"div",J:"ytp-ce-element-shadow"},{Z:"div",J:"ytp-ce-covering-image",W:KQ(w)},{Z:"div",J:"ytp-ce-covering-shadow-top"},{Z:"a",J:"ytp-ce-covering-overlay",W:{href:PX(D,w.targetUrl),tabindex:"-1"},K:[{Z:"div",uK:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.DM(w.title||"")},YU:w.title},{Z:"div",J:"ytp-ce-playlist-count",
K:[{Z:"div",J:"ytp-ce-playlist-icon"},{Z:"div",J:"ytp-ce-playlist-count-text",YU:w.playlistLength||void 0}]}]}]};Q=new g.B(D);break;case "CHANNEL":Q={Z:"div",uK:["ytp-ce-element","ytp-ce-channel",w.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":w.sa||"","aria-hidden":"true"},K:[{Z:"div",J:"ytp-ce-element-shadow"},{Z:"div",J:"ytp-ce-expanding-overlay",K:[{Z:"div",J:"ytp-ce-expanding-overlay-hider"},{Z:"div",J:"ytp-ce-expanding-overlay-background"},{Z:"div",J:"ytp-ce-expanding-overlay-content",
K:[{Z:"div",J:"ytp-ce-expanding-overlay-body",K:[{Z:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{Z:"a",uK:["ytp-ce-channel-title","ytp-ce-link"],W:{href:PX(D,w.targetUrl),target:"_blank",tabindex:"-1",dir:g.DM(w.title||"")},YU:w.title},w.subscribeButton?{Z:"div",J:"ytp-ce-subscribe-container",K:[{Z:"div",J:"ytp-ce-channel-subscribe"}]}:"",w.subscribersText?{Z:"div",J:"ytp-ce-channel-subscribers-text",W:w.sa?{"aria-hidden":"true"}:{},YU:w.subscribersText}:"",w.metadata?{Z:"div",uK:["ytp-ce-channel-metadata",
"yt-ui-ellipsis","yt-ui-ellipsis-3"],YU:w.metadata}:""]}]}]}]},{Z:"div",J:"ytp-ce-expanding-image",W:KQ(w)}]};Q=new g.B(Q);let t=g.ko(document,"div","ytp-ce-channel-subscribe",Q.element)[0];if(w.subscribeButton&&w.channelId){g.Hg(t,"ytp-ce-subscribe-button");let O;if(D.player.X().D){var Y=null;O=w.sessionData.itct}else Y="endscreen",O=null;Y=new g.IP(w.subscribeButton.subscribeText,w.subscribeButton.subscribeCount,w.subscribeButton.unsubscribeText,w.subscribeButton.unsubscribeCount,!!w.subscribeButton.enabled,
!!w.subscribeButton.classic,w.channelId,!!w.subscribeButton.subscribed,Y,O,D.player,!1);t.appendChild(Y.element);D.V.push(Y)}break;case "WEBSITE":D={Z:"div",uK:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":w.sa||"","aria-hidden":"true"},K:[{Z:"div",J:"ytp-ce-element-shadow"},{Z:"div",J:"ytp-ce-expanding-overlay",K:[{Z:"div",J:"ytp-ce-expanding-overlay-hider"},{Z:"div",J:"ytp-ce-expanding-overlay-background"},{Z:"div",J:"ytp-ce-expanding-overlay-content",K:[{Z:"div",J:"ytp-ce-expanding-overlay-body",
K:[{Z:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{Z:"div",J:"ytp-ce-website-title",W:{dir:g.DM(w.title||"")},YU:w.title},{Z:"div",J:"ytp-ce-website-metadata",YU:w.metadata},{Z:"a",uK:["ytp-ce-website-goto","ytp-ce-link"],W:{href:PX(D,w.targetUrl),target:"_blank",tabindex:"-1"},YU:w.callToAction}]}]}]}]},{Z:"div",J:"ytp-ce-expanding-image",W:KQ(w)},{Z:"div",J:"ytp-ce-expanding-icon",W:Hti(w.iconUrl)}]};Q=new g.B(D);break;case "CREATOR_MERCHANDISE":Q="",w.productPrice&&(Q={Z:"div",J:"ytp-ce-merchandise-price-container",
K:[{Z:"div",J:"ytp-ce-merchandise-price",YU:w.productPrice}]},w.additionalFeesText&&Q.K.push({Z:"div",J:"ytp-ce-merchandise-additional-fees",YU:w.additionalFeesText})),D={Z:"div",uK:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":w.sa||"","aria-hidden":"true"},K:[{Z:"div",J:"ytp-ce-element-shadow"},{Z:"div",J:"ytp-ce-expanding-overlay",K:[{Z:"div",J:"ytp-ce-expanding-overlay-hider"},{Z:"div",J:"ytp-ce-expanding-overlay-background"},{Z:"div",J:"ytp-ce-expanding-overlay-content",
K:[{Z:"div",J:"ytp-ce-expanding-overlay-body",K:[{Z:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{Z:"div",J:"ytp-ce-merchandise-title",W:{dir:g.DM(w.title||"")},YU:w.title},Q,{Z:"div",J:"ytp-ce-merchandise-metadata",YU:w.metadata},{Z:"a",uK:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:PX(D,w.targetUrl),target:"_blank",tabindex:"-1"},YU:w.callToAction}]}]}]}]},{Z:"div",J:"ytp-ce-expanding-image",W:KQ(w)},{Z:"div",J:"ytp-ce-merchandise-invideo-cta-container",K:[{Z:"div",J:"ytp-ce-merchandise-invideo-cta",
YU:w.callToAction||void 0}]}]},Q=new g.B(D)}w.isPlaceholder&&g.Hg(Q.element,"ytp-ce-placeholder");return Q},eFi=function(D,w,Q){function Y(){n(1)}
function t(){n(-1)}
w.listen("mouseenter",()=>{UW(D,w,Q)});
w.listen("mouseleave",()=>{cX(D,w,Q)});
D.player.X().D||w.listen("click",()=>{g.Hg(w.element,"ytp-ce-element-hover")});
w.listen("click",X=>{Eub(D,Q,X)});
w.listen("keypress",X=>{Eub(D,Q,X)});
w.listen("focus",()=>{UW(D,w,Q)});
w.listen("blur",()=>{cX(D,w,Q)});
w.listen("touchstart",()=>{UW(D,w,Q)});
var O=g.Z_("ytp-ce-expanding-overlay-hider",w.element);O&&w.B(O,"touchstart",X=>{X.stopPropagation();g.jl(w.element,"ytp-ce-element-hover");g.jl(w.element,"ytp-ce-force-expand")});
w.listen("keydown",X=>{D.aN=X.keyCode===9&&!X.shiftKey});
var n=X=>{D.N+=X;D.N>0?(g.Hg(w.element,"ytp-ce-force-expand"),hR(D,Q.id,!0)):(g.jl(w.element,"ytp-ce-force-expand"),g.jl(w.element,"ytp-ce-element-hover"),hR(D,Q.id,!1))};
O=X=>{X&&(w.listen("blur",()=>{X.style.display!="none"&&D.aN&&X.focus()}),w.B(X,"focus",Y),w.B(X,"blur",t))};
O(g.Z_("ytp-sb-subscribe",w.element));O(g.Z_("ytp-sb-unsubscribe",w.element));w.listen("focus",Y);w.listen("blur",t)},rW=function(D,w,Q){function Y(){O||(t++,t===w.length&&(n.stop(),Q&&Q()))}
if(!w||w.length===0||Tq(D))Q&&Q();else{w=j0s(D,w);var t=0,O=!1,n=new g.U5(()=>{O=!0;Q&&Q()},1E3,D);
n.start();for(D=0;D<w.length;D++)g.IC(w[D],Y)}},KQ=function(D){if(D.RV)var w=D.RV.thumbnails;
return Hti(w?w[w.length-1].url:null)},PX=function(D,w){D=D.player.X();
if(w){if(w.startsWith("//"))return D.protocol+":"+w;if(w.startsWith("/"))return g.Fc(D)+w}else return"";return w},Hti=function(D){return D?{style:"background-image: url("+D+")"}:{}},UW=function(D,w,Q){g.bQ(w.element,"ytp-ce-element-hover")||(Q.type==="VIDEO"||Q.type==="PLAYLIST"?g.Hg(w.element,"ytp-ce-element-hover"):D.player.X().D?(new g.U5(()=>{g.Hg(w.element,"ytp-ce-element-hover")},200)).start():g.Hg(w.element,"ytp-ce-element-hover"),rW(D,Q.e2),hR(D,Q.id,!0))},cX=function(D,w,Q){g.jl(w.element,
"ytp-ce-element-hover");
g.jl(w.element,"ytp-ce-force-expand");hR(D,Q.id,!1)},Eub=function(D,w,Q){if(w.targetUrl&&(!Q||Q.type!=="keypress"||Q.keyCode===13)){for(var Y=Q.target;Y&&!g.bQ(Y,"ytp-ce-element");){g.bQ(Y,"subscribe-label")&&LQ(D,w);
if(g.bQ(Y,"ytp-ce-channel-subscribe"))return;Y=Y.parentElement||null}if(!Y||g.bQ(Y,"ytp-ce-element-hover")){Q.preventDefault();Q.stopPropagation();if(Y=D.S[w.id])cX(D,Y,w),Y.element.blur();if(Q.ctrlKey||Q.metaKey||w.Xy==="new")LQ(D,w),D.player.sendVideoStatsEngageEvent(17,void 0),D.player.pauseVideo(),Q=g.P0(PX(D,w.targetUrl)),Q=g.Nv(Q),g.k4(Q,void 0,w.sessionData);else{let t=g.Jb(D.player.X())||D.player.getVideoData().wx,O=()=>{var n=PX(D,w.targetUrl),X=w.sessionData,W=w.watchEndpoint,v=g.uN(n);
t&&v&&(v.v||v.list)?D.player.lZ(v.v,X,v.list,!1,void 0,W||void 0):g.AW(n,X)};
LQ(D,w,()=>{D.player.sendVideoStatsEngageEvent(17,O)})}}}},hR=function(D,w,Q){D.D&&(Q?D.G.show():D.G.hide());
for(let Y of Object.keys(D.S))Y!==w&&g.s5(D.S[Y].element,"ytp-ce-element-shadow-show",Q)},LQ=function(D,w,Q){rW(D,w.clickUrls,Q);
(D=g.fu())&&w.IQ&&g.Zu(D,w.visualElement)},j0s=function(D,w){var Q=D.player.getVideoData().clientPlaybackNonce;
D=D.player.getCurrentTime().toFixed(2);Q={CPN:Q,AD_CPN:Q,MT:D};D=[];for(let Y=0;Y<w.length;Y++)D.push(zFO(w[Y],Q));return D},zFO=function(D,w){return D.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,Q=>{var Y=unescape(Q);
Y=Y.substring(1,Y.length-1);return w[Y]?escape(w[Y]):Q})},s0V=function(D){return typeof D==="string"?D:""},eo=function(D,w,Q){for(let Y in w)if(w[Y]===D)return D;
return Q},bL=function(D){if(!D)return null;
var w=g.P0(s0V(D.value));w=g.Nv(w);if(!w)return null;var Q=eo(D.target,mJm,"current");if(Q==null)D=null;else{var Y=D.show_link_icon;D=new AQO(w,Q,Y==="true"||Y==="false"?Y==="true":!0,D.pause_on_navigation!=null?D.pause_on_navigation:!0)}return D},Duy=function(D){if(!D)return null;
var w=eo(D.type,kjx),Q=eo(D.trigger,Zt$);D=D.url;D=Array.isArray(D)&&D.length?D[0]:D;D=bL(D?D:null);return w?new B3s(w,Q,D):null},wEx=function(D,w){return g.An(D.action,w)},HX=function(D,w){D="background-image: url("+D+");";
var Q=[];w&&Q.push(w);return{Z:"div",J:"iv-card-image",W:{style:D},K:Q}},jo=function(D){return D.customMessage?EW("div","iv-card-message",D.customMessage):""},zq=function(D){if(!D.metaInfo||D.metaInfo.length===0)return"";
var w=[];for(let Q of D.metaInfo)w.push(EW("li","",Q));return{Z:"ul",J:"iv-card-meta-info",K:w}},sW=function(D,w,Q,Y){if(Y)for(let t of w)D.Y(t,Y,Q.id,Q.sessionData,Q.dZ.click,5)},EW=function(D,w,Q){w?typeof w==="string"?w={"class":w}:Array.isArray(w)&&(w={"class":w.join(" ")}):w={};
w.dir=g.DM(Q);return{Z:D,W:w,YU:Q}},Qny=function(D){if(!D.customMessage)return"";
var w=["iv-card-action","iv-card-primary-link"],Q={};D.mA&&(w.push("iv-card-action-icon"),Q.style="background-image: url("+D.mA+");");Q.dir=g.DM(D.customMessage);var Y=[{Z:"span",YU:D.customMessage}];D.showLinkIcon&&(Y.push("\u00a0"),Y.push({Z:"span",J:"iv-card-link-icon"}));return{Z:"div",uK:w,W:Q,K:Y}},Ysx=function(D){var w;
(w=D)&&!(w=D.length>1?D.charAt(0)==="/"&&D.charAt(1)!=="/":D==="/")&&(w=D.replace(/^(https?:)?\/\//,"").split("/",1),w=!w||w.length<1||!w[0]?[]:w[0].toLowerCase().split(".").reverse(),w=w[0]==="com"&&w[1]==="youtube"||w[0]==="be"&&w[1]==="youtu");return w?D.indexOf("/redirect?")===-1:!1},t7P=function(D,w){return w?w:Ysx(D)?"current":"new"},ma=function(D,w,Q,Y,t,O,n){D.context.Y.listen(w,"click",X=>{D.XL(Q,Y,t,O||[],n||0,X)});
D.context.Y.listen(w,"touchstart",()=>{D.Uv=!1});
D.context.Y.listen(w,"touchmove",()=>{D.Uv=!0})},O_V=function(D){if(g.H(D,g.dQ)?.url)return g.H(D,g.dQ).url;
if((D=g.H(D,g.OZ))&&D.videoId){let w="/watch?v="+D.videoId;D.playlistId&&(w+="&list="+D.playlistId);D.index&&(w+="&index="+D.index);D.startTimeSeconds&&(w+="&t="+D.startTimeSeconds);return w}return null},AR=function(D,w,Q){return{C_:(D.impressionLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||""),
click:(Q.loggingUrls||[]).map(Y=>Y.baseUrl||""),
close:(w.dismissLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||""),
B3:(w.impressionLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||""),
nX:(w.clickLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||"")}},D1=function(D,w){if(w.onClickCommand&&g.H(w.onClickCommand,g.aUr)?.targetId==="engagement-panel-error-corrections"){D.ma=w;
var Q=!0}else Q=!1;if(!Q||$uy(D,w))if(Q=npY(D,w)){var Y={tL:w,mj:Q.element,G1:!1};if(w.onClickCommand)D.L.A("web_infocards_teaser_show_logging_fix")&&(D.Ry||Wws(D),kf(D,w.id),Q=D.findLastIndex(Y),g.Si(D.cards,Q,0,Y));else{D.isInitialized||XEm(D);kf(D,w.id);let t=D.findLastIndex(Y);g.Si(D.cards,t,0,Y);Q.ZV(D.S,t);D.jQ()}w.autoOpen?D.addCueRange(w.startMs,0x8000000000000,w.id,()=>{D.D||(D.Y=Y,ZO(D),vpy(D,Y),BX(D,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(Q=D.context.L.getCurrentTime()*1E3,Q<5E3&&Q>w.startMs&&
V7P(D,Y),D.addCueRange(w.startMs,w.startMs+1,w.id,()=>{V7P(D,Y)}),ZO(D))}},wu=function(D){D.D&&(D.Pt.hide(),D.Np.S(),g.jl(D.context.L.getRootNode(),g.tw.IV_DRAWER_OPEN),D.D=!1,Gq(D.L),D.G&&D.G.stop(),D.G=new g.U5(()=>{D.yl&&(D.yl.focus(),D.yl=null)},330),D.G.start())},Ss$=function(D,w){w=w.data;
w.autoOpenMs&&D.addCueRange(w.autoOpenMs,0x8000000000000,"",()=>{BX(D,"YOUTUBE_DRAWER_AUTO_OPEN")});
w.autoCloseMs&&D.addCueRange(w.autoCloseMs,0x8000000000000,"",()=>{wu(D)});
var Q=w.headerText;g.JM(D.Sk,Q);D.V&&D.V.setAttribute("data-tooltip-title",Q);w.eventId&&(D.eventId=w.eventId);D.bK=g.v3(w.trackingParams);D.N=g.v3(w.closeTrackingParams);D.DF=g.v3(w.iconTrackingParams)},Qj=function(D,w,Q){var Y=-1,t=-1;
for(let O=0;O<D.length;O++){if(D[O].height===w||D[O].width===Q)return D[O];((D[O].height||0)<w||(D[O].width||0)<Q)&&(Y<0||(D[Y].height||0)<(D[O].height||0)||(D[Y].width||0)<(D[O].width||0))?Y=O:((D[O].height||0)>=w||(D[O].width||0)>=Q)&&(t<0||(D[t].height||0)>(D[O].height||0)||(D[t].width||0)>(D[O].width||0))&&(t=O)}return D[t>=0?t:Y]},Ye=function(D,w,Q,Y){return{feature:Q.feature?Q.feature:"cards",
src_vid:D.context.videoData.videoId,annotation_id:w,ei:D.context.videoData.eventId||"",itct:Y.trackingParams||""}},leP=function(D,w){var Q=w.cardId?w.cardId:`cr:${D.C}`,Y=D.L.X().experiments.IN("enable_error_corrections_infocard_web_client");
if(!w.content&&w.teaser.simpleCardTeaserRenderer&&Y){Y=w.teaser.simpleCardTeaserRenderer;var t=w.icon?w.icon.infoCardIconRenderer:null;if(Y.channelAvatar&&Y.channelAvatar.thumbnails&&Y.channelAvatar.thumbnails.length>0)var O=Qj(Y.channelAvatar.thumbnails,22,22).url;w={id:Q,timestamp:D.C,type:"simple",teaserText:g.$4(Y.message),teaserDurationMs:Number(w.cueRanges[0].teaserDurationMs),startMs:Number(w.cueRanges[0].startCardActiveMs),autoOpen:!!w.autoOpen,sessionData:{},sponsored:!1,dZ:{},QN:null,I6:Y.trackingParams?
g.v3(Y.trackingParams):null,DF:t&&t.trackingParams?g.v3(t.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,mA:null,title:"",customMessage:"",url:null,onClickCommand:Y.onTapCommand||null,yE:O};D1(D,w)}else if(w.content?.simpleCardContentRenderer){if(!w.cueRanges.length)return;O=w.content?.simpleCardContentRenderer;Y=w.teaser.simpleCardTeaserRenderer;t=w.icon?w.icon.infoCardIconRenderer:null;w={id:Q,timestamp:D.C,type:"simple",teaserText:g.$4(Y.message),teaserDurationMs:Number(w.cueRanges[0].teaserDurationMs),
startMs:Number(w.cueRanges[0].startCardActiveMs),autoOpen:!!w.autoOpen,sessionData:Ye(D,Q,w,O),sponsored:!1,dZ:AR(O,Y,O.command),QN:O.trackingParams?g.v3(O.trackingParams):null,I6:Y.trackingParams?g.v3(Y.trackingParams):null,DF:t&&t.trackingParams?g.v3(t.trackingParams):null,imageUrl:Qj(O.image.thumbnails,290,290).url,displayDomain:O.displayDomain?g.$4(O.displayDomain):null,showLinkIcon:!!O.showLinkIcon,mA:null,title:O.title?g.$4(O.title):"",customMessage:O.callToAction?g.$4(O.callToAction):"",url:g.H(O.command,
g.dQ).url?bL({pause_on_navigation:!D.context.videoData.isLivePlayback,target:"new",value:g.H(O.command,g.dQ).url}):null,onClickCommand:null};D1(D,w)}else if(w.content?.collaboratorInfoCardContentRenderer){if(!w.cueRanges.length)return;O=w.content?.collaboratorInfoCardContentRenderer;Y=w.teaser.simpleCardTeaserRenderer;t=w.icon?w.icon.infoCardIconRenderer:null;w={id:Q,timestamp:D.C,type:"collaborator",teaserText:g.$4(Y.message),teaserDurationMs:Number(w.cueRanges[0].teaserDurationMs),startMs:Number(w.cueRanges[0].startCardActiveMs),
autoOpen:!!w.autoOpen,sessionData:Ye(D,Q,w,O),sponsored:!1,dZ:AR(O,Y,O.endpoint),QN:O.trackingParams?g.v3(O.trackingParams):null,I6:Y.trackingParams?g.v3(Y.trackingParams):null,DF:t&&t.trackingParams?g.v3(t.trackingParams):null,channelId:g.H(O.endpoint,g.yY).browseId,customMessage:O.customText?g.$4(O.customText):null,profileImageUrl:Qj(O.channelAvatar.thumbnails,290,290).url,title:O.channelName?g.$4(O.channelName):"",metaInfo:[O.subscriberCountText?g.$4(O.subscriberCountText):""],url:bL({pause_on_navigation:!D.context.videoData.isLivePlayback,
target:"new",value:g.H(O.endpoint,g.yY).canonicalBaseUrl?g.H(O.endpoint,g.yY).canonicalBaseUrl:`/channel/${g.H(O.endpoint,g.yY).browseId}`}),onClickCommand:null};D1(D,w)}else if(w.content?.playlistInfoCardContentRenderer){if(!w.cueRanges.length)return;O=w.content?.playlistInfoCardContentRenderer;Y=w.teaser.simpleCardTeaserRenderer;t=w.icon?w.icon.infoCardIconRenderer:null;w={id:Q,timestamp:D.C,type:"playlist",teaserText:g.$4(Y.message),teaserDurationMs:Number(w.cueRanges[0].teaserDurationMs),startMs:Number(w.cueRanges[0].startCardActiveMs),
autoOpen:!!w.autoOpen,sessionData:Ye(D,Q,w,O),sponsored:!1,dZ:AR(O,Y,O.action),QN:O.trackingParams?g.v3(O.trackingParams):null,I6:Y.trackingParams?g.v3(Y.trackingParams):null,DF:t&&t.trackingParams?g.v3(t.trackingParams):null,GJ:Qj(O.playlistThumbnail.thumbnails,258,290).url,customMessage:O.customMessage?g.$4(O.customMessage):null,playlistVideoCount:g.$4(O.playlistVideoCount),title:O.playlistTitle?g.$4(O.playlistTitle):"",metaInfo:[O.channelName?g.$4(O.channelName):"",O.videoCountText?g.$4(O.videoCountText):
""],url:bL({pause_on_navigation:!D.context.videoData.isLivePlayback,target:"new",value:O_V(O.action)}),onClickCommand:null};D1(D,w)}else if(w.content?.videoInfoCardContentRenderer){if(!w.cueRanges.length)return;O=w.content?.videoInfoCardContentRenderer;Y=w.teaser.simpleCardTeaserRenderer;t=w.icon?w.icon.infoCardIconRenderer:null;w={id:Q,timestamp:D.C,type:"video",teaserText:g.$4(Y.message),teaserDurationMs:Number(w.cueRanges[0].teaserDurationMs),startMs:Number(w.cueRanges[0].startCardActiveMs),autoOpen:!!w.autoOpen,
sessionData:Ye(D,Q,w,O),sponsored:!1,dZ:AR(O,Y,O.action),QN:O.trackingParams?g.v3(O.trackingParams):null,I6:Y.trackingParams?g.v3(Y.trackingParams):null,DF:t&&t.trackingParams?g.v3(t.trackingParams):null,GJ:Qj(O.videoThumbnail.thumbnails,258,290).url,videoDuration:O.lengthString?g.$4(O.lengthString):null,customMessage:O.customMessage?g.$4(O.customMessage):null,title:O.videoTitle?g.$4(O.videoTitle):"",metaInfo:[O.channelName?g.$4(O.channelName):"",O.viewCountText?g.$4(O.viewCountText):""],isLiveNow:!!O.badge,
url:bL({pause_on_navigation:!D.context.videoData.isLivePlayback,target:"new",value:O_V(O.action)}),onClickCommand:null};D1(D,w)}D.C++},fem=function(D,w){return g.An(D.cards,Q=>Q.tL.id===w)},ZO=function(D){g.s5(D.L.getRootNode(),"ytp-cards-shopping-active",yib(D))},kf=function(D,w){if(w=fem(D,w))w===D.Y&&(D.Y=null),D.L.removeCueRange(w.tL.id),g.fG(w.mj),g.YY(D.cards,w),D.jQ(),ZO(D)},BX=function(D,w,Q){if(!D.D){D.Pt.show();
D.JN=new g.U5(()=>{g.Hg(D.context.L.getRootNode(),g.tw.IV_DRAWER_OPEN)},0);
D.JN.start();D.Np.B(D.S,"mousewheel",t=>{D.Ht.start();t.preventDefault();t=t||window.event;var O=0;t.type=="MozMousePixelScroll"?O=0==(t.axis==t.HORIZONTAL_AXIS)?t.detail:0:window.opera?O=t.detail:O=t.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?t.wheelDeltaY/-30:t.wheelDeltaY/-1.2:t.wheelDelta/-1.6:t.wheelDeltaY/-3;if(t=O)D.S.scrollTop+=t});
D.D=!0;var Y=g.fu();Y&&D.bK&&D.N&&g.A9(Y,[D.bK,D.N]);w={TRIGGER_TYPE:w};for(let t of D.cards)t.G1||(t.G1=!0,Ji$(D.context.logger,t.tL.dZ.C_,w)),Y&&g.A9(Y,[t.tL.QN]);Gq(D.L);Q&&(D.G=new g.U5(()=>{D.yl=D.V;D.lK.focus()},330),D.G.start())}},XEm=function(D){g.E5(D.Di(),[g.tw.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.PA(D.L,D.j,5);D.AO();D.V=g.Z_("ytp-cards-button",D.L.getRootNode());D.lK=g.Z_("iv-drawer-close-button",D.j);D.isInitialized=!0},Wws=function(D){D.aN.push(g.sg("iv-teaser-shown",D.mC,D));
D.aN.push(g.sg("iv-teaser-hidden",D.RD,D));D.aN.push(g.sg("iv-teaser-clicked",D.V2,D));D.Ry=!0},$uy=function(D,w){D.ma=w;
var Q=D.L.getVideoData();if(!Q)return!1;Q=g.bu(Q.getWatchNextResponse());if(Q?.markersMap)for(let t=0;Q?.markersMap.length>t;t++){var Y=Q?.markersMap[t];if(Y.key==="ERROR_CORRECTION_MARKERS"&&(Y=Y.value?.markers)&&Y.length>0)return w.startMs=g.H(Y[0],g.DYC)?.timeRangeStartMillis||0,D.ma=null,!0}return!1},npY=function(D,w){switch(w.type){case "simple":D=D.g$;
var Q=w.displayDomain?{Z:"div",J:"iv-card-image-text",YU:w.displayDomain}:void 0;var Y=Qny(w);Q={Z:"div",uK:["iv-card"],K:[{Z:"a",J:"iv-click-target",W:{href:w.url?w.url.Y()||"":""},K:[HX(w.imageUrl,Q),{Z:"div",J:"iv-card-content",K:[EW("h2",void 0,w.title),Y]}]}]};Q=new g.B(Q);sW(D,g.A3("iv-click-target",Q.element),w,w.url);w=Q;break;case "collaborator":D=D.g$;Q={Z:"div",uK:["iv-card","iv-card-channel"],K:[{Z:"a",uK:["iv-click-target"],W:{href:w.url.Y()||"","data-ytid":w.channelId},K:[HX(w.profileImageUrl),
{Z:"div",J:"iv-card-content",K:[jo(w),{Z:"h2",J:"iv-card-primary-link",YU:w.title},zq(w)]}]}]};Q=new g.B(Q);sW(D,g.A3("iv-click-target",Q.element),w,w.url);w=Q;break;case "playlist":D=D.g$;Q={Z:"div",uK:["iv-card","iv-card-playlist"],K:[{Z:"a",J:"iv-click-target",W:{href:w.url.Y()||""},K:[HX(w.GJ,{Z:"div",J:"iv-card-image-overlay",K:[{Z:"span",J:"iv-card-playlist-video-count",YU:w.playlistVideoCount}]}),{Z:"div",J:"iv-card-content",K:[jo(w),EW("h2","iv-card-primary-link",w.title),zq(w)]}]}]};Q=new g.B(Q);
sW(D,g.A3("iv-click-target",Q.element),w,w.url);w=Q;break;case "productListing":D=D.g$;var t=w.offers.length!=0;Q=["iv-card"];Y="";var O=Qny(w);t&&(Q.push("iv-card-product-listing"),Y="iv-card-primary-link",O=w.offers[0],t=[],O.price&&t.push({Z:"div",J:"iv-card-offer-price",YU:O.price}),O.merchant&&t.push({Z:"div",J:"iv-card-offer-merchant",YU:O.merchant}),O={Z:"div",K:t});t=w.url?w.url.Y()||"":"";Q={Z:"div",uK:Q,W:{tabindex:"0"},K:[{Z:"a",uK:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
w.imageUrl+");",href:t,"aria-hidden":"true",tabindex:"-1"}},{Z:"div",J:"iv-card-content",K:[w.sponsored?{Z:"div",J:"iv-card-sponsored",K:["Sponsored",{Z:"div",J:"iv-ad-info-container",K:[{Z:"div",J:"iv-ad-info",YU:"{{adInfo}}"},{Z:"div",J:"iv-ad-info-icon-container",K:[{Z:"div",J:"iv-ad-info-icon"},{Z:"div",J:"iv-ad-info-callout"}]}]}]}:"",{Z:"a",J:"iv-click-target",W:{href:t},K:[EW("h2",Y,w.title),O]}]}]};Q=new g.B(Q);Y=g.WO("span");g.JM(Y,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
Q.setContent(Y,"adInfo");sW(D,g.A3("iv-click-target",Q.element),w,w.url);w=Q;break;case "video":D=D.g$;Q=w.isLiveNow?{Z:"span",uK:["yt-badge","yt-badge-live"],YU:"LIVE NOW"}:null;Q={Z:"div",uK:["iv-card","iv-card-video"],K:[{Z:"a",J:"iv-click-target",W:{href:w.url?.Y()||""},K:[HX(w.GJ,w.videoDuration?{Z:"span",J:"iv-card-video-duration",YU:w.videoDuration}:void 0),{Z:"div",J:"iv-card-content",K:[jo(w),EW("h2","iv-card-primary-link",w.title),zq(w),Q]}]}]};Q=new g.B(Q);sW(D,g.A3("iv-click-target",Q.element),
w,w.url);w=Q;break;default:return null}return w},V7P=function(D,w){if(!g.bQ(D.L.getRootNode(),"ytp-cards-teaser-shown")){if(D.Y!==w){var Q=g.fu(),Y=D.Y?D.Y.tL.DF:D.DF;
Q&&Y&&g.kl(Q,[Y]);D.Y=w;ZO(D)}(Q=D.isInitialized&&D.Di().style.display=="none")||(Q=D.context.L.getPlayerState(),Y=Q===0&&D.context.L.getCurrentTime()===0,Q=!(Q===1||Q===3||Y));Q||w.tL.teaserDurationMs&&D.L.WM(!0,{teaserText:w.tL.teaserText,durationMs:w.tL.teaserDurationMs,onClickCommand:w.tL.onClickCommand,yE:w.tL.yE??null});D.Ev.isActive()||((!D.D||!D.Ht.isActive()&&D.Ga)&&vpy(D,w),D.Ev.start(910+w.tL.teaserDurationMs))}},yib=function(D){return D.Y?D.Y.tL.type==="productListing":D.L.A("enable_wn_infocards")?
!!D.cards?.length&&g.sU(D.cards,w=>w.tL.type==="productListing"):g.sU(D.cards,w=>w.tL.type==="productListing")},vpy=function(D,w){D.O.wv?(w=new CQ([0,
D.S.scrollTop],[0,w.mj.offsetTop],600,UJM),D.context.D.listen(w,"animate",Q=>{D.S.scrollTop=Q.y}),D.context.D.listen(w,"finish",Q=>{D.S.scrollTop=Q.y}),w.play()):(D.O.Eo(!0),D.S.scrollTop=w.mj.offsetTop,D.O.Eo(!1))},tX=function(D){return D.Y&&D.Y.tL?D.Y.tL:D.cards[0]&&D.cards[0].tL?D.cards[0].tL:null},pEA=function(D){var w=D.annotation.data;
"start_ms"in w&&"end_ms"in w&&D.addCueRange(Number(w.start_ms),Number(w.end_ms),D.annotation.id,()=>{D.show()},()=>{D.hide()})},M7b=function(D,w){var Q=qq$(w).width;
g.jf(w,Q);Q=new qp(w,[Q,w.offsetTop],[Q-Q,w.offsetTop],200,Pji);g.P(D,Q);D.context.D.listen(Q,"begin",()=>{g.wE(w,!0)});
Q.play()},OR=function(D,w,Q){Q.stopPropagation();
aey(D);gpu(D,w);D.Y.focus()},GHb=function(D){var w=D.annotation.data;
if(D.annotation.style==="cta")var Q=6;else if(D.annotation.style==="video"||D.annotation.style==="playlist")Q=7;D.C=w.collapsedelay_ms||D.C;var Y=["iv-promo","iv-promo-inactive"];D.Di().setAttribute("aria-hidden","true");D.Di().setAttribute("aria-label","Promotion");D.Di().tabIndex=0;var t=D.annotation.R7(),O=w.image_url;if(O){var n=D.createElement({Z:"div",uK:["iv-promo-img","iv-click-target"]});O=D.createElement({Z:"img",W:{src:O,"aria-hidden":"true"}});n.appendChild(O);w.video_duration&&!w.is_live?
(O=D.createElement({Z:"span",J:"iv-promo-video-duration",YU:w.video_duration}),n.appendChild(O)):w.playlist_length&&(O=D.createElement({Z:"span",J:"iv-promo-playlist-length",YU:w.playlist_length.toString()}),n.appendChild(O));t&&ma(D,n,t,D.annotation.id,w.session_data,void 0,Q)}t?(O=D.createElement({Z:"a",J:"iv-promo-txt"}),g.h4(O,t.Y()),D.Y=O):D.Y=D.createElement({Z:"div",J:"iv-promo-txt"});switch(D.annotation.style){case "cta":case "website":var X=D.createElement({Z:"p",K:[{Z:"strong",YU:w.text_line_1}]});
var W=D.createElement({Z:"p",K:[{Z:"span",J:"iv-promo-link",YU:w.text_line_2}]});if(O=w.text_line_3){Y.push("iv-promo-website-card-cta-redesign");var v=D.createElement({Z:"button",uK:["iv-promo-round-expand-icon","ytp-button"]});O=D.createElement({Z:"button",uK:["iv-button","iv-promo-button"],K:[{Z:"span",J:"iv-button-content",YU:O}]});var V=D.createElement({Z:"div",J:"iv-promo-button-container"});V.appendChild(O);t&&ma(D,D.Di(),t,D.annotation.id,w.session_data,void 0,Q)}g.Hg(D.Y,"iv-click-target");
t&&ma(D,D.Y,t,D.annotation.id,w.session_data,void 0,Q);break;case "playlist":case "video":X=D.createElement({Z:"p",K:[{Z:"span",YU:w.text_line_1}]}),W=D.createElement({Z:"p",K:[{Z:"strong",YU:w.text_line_2}]}),w.is_live&&(X=W,W=D.createElement({Z:"span",uK:["yt-badge","iv-promo-badge-live"],YU:"LIVE NOW"})),g.Hg(D.Y,"iv-click-target"),t&&ma(D,D.Y,t,D.annotation.id,w.session_data,void 0,Q),Y.push("iv-promo-video")}X&&D.Y.appendChild(X);W&&D.Y.appendChild(W);D.N.appendChild(D.Y);V&&D.N.appendChild(V);
Q=D.createElement({Z:"div",J:"iv-promo-actions"});D.S=D.createElement({Z:"button",uK:["iv-promo-expand","ytp-button"]});D.S.title="Expand";D.context.Y.listen(D.S,"click",y=>{OR(D,5E3,y)});
Q.appendChild(D.S);g.wE(D.S,!1);D.context.Y.listen(D.Di(),"mouseover",D.Ht,D);D.context.Y.listen(D.Di(),"mouseout",D.g$,D);D.context.Y.listen(D.Di(),"touchend",y=>{OR(D,5E3,y)});
D.D=D.createElement({Z:"button",uK:["iv-promo-close","ytp-button"]});D.D.title="Close";D.context.Y.listen(D.D,"click",D.annotation.style==="cta"&&w.text_line_3?D.ma:D.aN,D);Q.appendChild(D.D);g.E5(D.Di(),Y);n&&(g.Vk(D.Di(),n),v&&n.appendChild(v));g.Vk(D.Di(),D.N);g.Vk(D.Di(),Q)},$e=function(D){D.j&&(g.lx.clearTimeout(D.j),D.j=null)},aey=function(D){D.G.stop();
D.isCollapsed&&(g.zd(D.Di(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),D.isCollapsed=!1,D.Y&&D.Y.removeAttribute("aria-hidden"),g.wE(D.S,!1),g.wE(D.D,!0))},gpu=function(D,w){D.j||(D.j=g.Zi(function(){$e(this);
xuM(this)},w,D))},xuM=function(D){D.isCollapsed||D.V||D.j||(g.Hg(D.Di(),"iv-promo-collapsed"),D.isCollapsed=!0,D.G.start())},Ji$=function(D,w,Q){w&&(Q?n3(D,w.map(Y=>g.CL(Y,Q))):n3(D,w))},n3=function(D,w,Q,Y){var t=1,O=void 0,n=-1;
if(Q){let X=!1;O=()=>{t--;t||X||(clearTimeout(n),X=!0,Q())};
n=setTimeout(()=>{X=!0;Q()},1E3)}for(let X of w||[])t++,g.IC(X,O);
Y&&(t++,Y!==0&&D.L.sendVideoStatsEngageEvent(Y,O))},RVP=function(D){return D==="annotation-editor"||D==="live-dashboard"},opi=function(D){D.j&&(D.player.removeEventListener("videodatachange",D.j),D.j=null)},Fwi=function(D){D=D.createElement({Z:"div",
uK:["annotation","annotation-type-custom"]});g.wE(D,!1);return D},Wl=function(D,w){var Q=!1,Y=w.getElementsByTagName("annotations");
if(Y&&!(Y.length<1)&&(Y=Y[0].getAttribute("itct"))){var t=g.fu();if(t){var O=g.lt();O&&g.RY(g.rz)(void 0,t,O,[g.v3(Y)])}}w=w.getElementsByTagName("annotation");for(Y=0;Y<w.length;Y++){var n=Cfs(D,w[Y]);t=null;try{a:{if(!n){t=null;break a}var X=n.id;O=/.+/;let M=typeof X==="string"&&O!=null&&X!=null&&X.match(O)?X:"",R=eo(n.type,ufx),I=eo(n.style,qsi),c=s0V(n.data),h=c.length!==0?JSON.parse(c):{};b:{var W=n.action;O=Duy;if(W==null){var v=null;break b}if(g.Gx(W)){n=[];for(let b of W){let A=O(b);A&&n.push(A)}v=
n;break b}let L=O(W);v=L?[L]:[]}O=v;t=M&&R?new dus(M,R,I,O,h):null}}catch(M){}if(t)if(t.type==="branding"||t.type==="promotion"){O=D;n=t;var V=Fwi(O),y=null;switch(n.type){case "branding":if(O.player.X().be)break;O.player.A("web_player_overlay_positioned_layout")?(V.setAttribute("data-overlay-order","11"),O.player.dD(V,4,!0)):O.S.element.appendChild(V);y=new i_m(V,X2(O),n);break;case "promotion":g.PA(O.player,V,4),y=new N$u(V,X2(O),n)}y&&y.Ta();y&&(g.P(D,y),D.C[t.id]=y)}else if(t.type==="card"||t.type===
"drawer"){D.Y||(D.Y=T$m(D),g.P(D,D.Y));if(t.type==="card"){V=D.Y;var J=(Q=t)&&Q.data&&Q.data.card_type;t=Q.data;if(J)switch(O=t.tracking||{},O={C_:O.impression,click:O.click,close:O.close,B3:O.teaser_impression,nX:O.teaser_click},n=t.tracking_params||{},y=null,J){case "collaborator":Q={id:Q.id,timestamp:t.timestamp||0,type:t.card_type,teaserText:t.teaser_text,teaserDurationMs:t.teaser_duration_ms,startMs:t.start_ms,autoOpen:t.auto_open||!1,sessionData:t.session_data||{},sponsored:t.sponsored||!1,
dZ:O,QN:n.card?g.v3(n.card):null,I6:n.teaser?g.v3(n.teaser):null,DF:n.icon?g.v3(n.icon):null,channelId:t.channel_id,customMessage:t.custom_message?t.custom_message:null,profileImageUrl:t.image_url,title:t.title,metaInfo:t.meta_info,url:bL({pause_on_navigation:t.pause_on_navigation,target:t.target||"new",value:t.url}),onClickCommand:null};D1(V,Q);break;case "playlist":Q={id:Q.id,timestamp:t.timestamp||0,type:t.card_type,teaserText:t.teaser_text,teaserDurationMs:t.teaser_duration_ms,startMs:t.start_ms,
autoOpen:t.auto_open||!1,sessionData:t.session_data||{},sponsored:t.sponsored||!1,dZ:O,QN:n.card?g.v3(n.card):null,I6:n.teaser?g.v3(n.teaser):null,DF:n.icon?g.v3(n.icon):null,GJ:t.image_url,playlistVideoCount:t.playlist_video_count,customMessage:t.custom_message?t.custom_message:null,title:t.title,metaInfo:t.meta_info,url:bL({pause_on_navigation:t.pause_on_navigation,target:t.target||"new",value:t.url}),onClickCommand:null};D1(V,Q);break;case "productListing":t.signin_url&&(y=bL({target:"current",
value:t.signin_url}));J=[];let M=t.offers||[];for(let R=0;R<M.length;R++)J.push(new Ieu(g.lP(M[R].merchant),g.lP(M[R].price)));Q={id:Q.id,timestamp:t.timestamp||0,type:t.card_type,teaserText:t.teaser_text,teaserDurationMs:t.teaser_duration_ms,startMs:t.start_ms,autoOpen:t.auto_open||!1,sessionData:t.session_data||{},sponsored:t.sponsored||!1,dZ:O,QN:n.card?g.v3(n.card):null,I6:n.teaser?g.v3(n.teaser):null,DF:n.icon?g.v3(n.icon):null,imageUrl:t.image_url,displayDomain:t.display_domain?t.display_domain:
null,showLinkIcon:!!t.show_link_icon,mA:t.button_icon_url?t.button_icon_url:null,title:t.title,customMessage:t.custom_message?t.custom_message:null,url:bL({pause_on_navigation:t.pause_on_navigation,target:t.target||"new",value:t.url}),qQl:y,gYt:t.signin_title?t.signin_title:void 0,acN:t.signin_message?t.signin_message:void 0,offers:J,onClickCommand:null};D1(V,Q);break;case "simple":Q={id:Q.id,timestamp:t.timestamp||0,type:t.card_type,teaserText:t.teaser_text,teaserDurationMs:t.teaser_duration_ms,
startMs:t.start_ms,autoOpen:t.auto_open||!1,sessionData:t.session_data||{},sponsored:t.sponsored||!1,dZ:O,QN:n.card?g.v3(n.card):null,I6:n.teaser?g.v3(n.teaser):null,DF:n.icon?g.v3(n.icon):null,imageUrl:t.image_url,displayDomain:t.display_domain?t.display_domain:null,showLinkIcon:!!t.show_link_icon,mA:t.button_icon_url?t.button_icon_url:null,title:t.title,customMessage:t.custom_message?t.custom_message:null,url:bL({pause_on_navigation:t.pause_on_navigation,target:t.target||"new",value:t.url}),onClickCommand:null};
D1(V,Q);break;case "video":Q={id:Q.id,timestamp:t.timestamp||0,type:t.card_type,teaserText:t.teaser_text,teaserDurationMs:t.teaser_duration_ms,startMs:t.start_ms,autoOpen:t.auto_open||!1,sessionData:t.session_data||{},sponsored:t.sponsored||!1,dZ:O,QN:n.card?g.v3(n.card):null,I6:n.teaser?g.v3(n.teaser):null,DF:n.icon?g.v3(n.icon):null,GJ:t.image_url,videoDuration:t.video_duration||null,customMessage:t.custom_message?t.custom_message:null,title:t.title,metaInfo:t.meta_info,isLiveNow:!!t.is_live_now,
url:bL({pause_on_navigation:t.pause_on_navigation,target:t.target||"new",value:t.url}),onClickCommand:null},D1(V,Q)}}else Ss$(D.Y,t);Q=!0}}Q&&(Gq(D.player),D.O())},Kwu=function(D){var w=D.player.X();
D=D.player.getVideoData();return(w.annotationsLoadPolicy||D.annotationsLoadPolicy)===1&&!D.ZJ||w.Ga.get(D.videoId)||D.XG()||g.hY(D)?!0:!1},PfY=function(D,w){w=!w.isCued()&&!w.Y(1024);
D.S.Eo(w);D.D.Eo(w)},rim=function(D,w){var Q=w.videoId,Y=O=>{var n=D.loadNumber;
D.N=null;D.loaded&&D.loadNumber===n&&D.player.getVideoData().videoId===Q&&(O=g.Kw(O)&&O.responseXML?O.responseXML:null)&&(Wl(D,O),g.Hg(D.player.getRootNode(),"iv-module-loaded"))};
g.p9()&&(Y=Uuy(D,Y));var t={format:"XML",onFinish:Y,onError:()=>{D.N=null},
urlParams:{}};w.isPharma&&(t.urlParams.pharma="1");t.method="POST";t.withCredentials=!0;(Y=D.player.X().Ga.get(Q))&&cii(t,Y);Y=Y&&Y.m6;if(!w.iz||Y)D.j=()=>{if(!D.ma)D.onVideoDataChange(t);var O=D.player.getVideoData();O?.yL()&&!D.aN&&hVA(D,O)},D.player.addEventListener("videodatachange",D.j)},vl=function(D,w){var Q=!1;
D.Y||(D.Y=T$m(D),g.P(D,D.Y));for(var Y of w.cards||[])Y.cardRenderer&&(leP(D.Y,Y.cardRenderer),Q=!0);Q&&(D.player.getVideoData()?.yL()||(Q=D.Y,Y=w.headerText?g.$4(w.headerText):"",g.JM(Q.Sk,Y),Q.V&&Q.V.setAttribute("data-tooltip-title",Y),Q.context.videoData.eventId&&(Q.eventId=Q.context.videoData.eventId),Q.bK=w.trackingParams?g.v3(w.trackingParams):null,Q.N=w.closeButton.infoCardIconRenderer.trackingParams?g.v3(w.closeButton.infoCardIconRenderer.trackingParams):null,Q.DF=w.icon.infoCardIconRenderer.trackingParams?
g.v3(w.icon.infoCardIconRenderer.trackingParams):null,D.O()),Gq(D.player))},hVA=function(D,w){if(w=w.getWatchNextResponse()?.cards?.cardCollectionRenderer)D.aN=!0,vl(D,w),w.headerText&&D.VJ&&(w=g.$4(w.headerText),D.VJ.setAttribute("data-tooltip-title",w))},Uuy=function(D,w){return(...Q)=>{D.Lt()||D.Ta.push(g.qr.Ln(()=>{w(...Q)}))}},cii=function(D,w){D.method="POST";
D.postParams=D.postParams||{};w.m6&&(D.postParams.ic_coll=w.m6);w.P3&&(D.postParams.ic_track=w.P3)},Cfs=function(D,w){var Q={};
for(var Y of w.attributes)Q[Y.name]=Y.nodeValue;for(Y=0;Y<w.childNodes.length;Y++){let O=w.childNodes[Y];if(!g.xA(O)||O.nodeType!=1)continue;var t=void 0;if(Q[O.tagName])t=Q[O.tagName];else if(O.tagName==="data"){O.childNodes.length>0&&(t=O.childNodes[0].nodeValue,Q[O.tagName]=typeof t==="string"?t.trim():t);continue}else t=[],Q[O.tagName]=t;O&&O.tagName==="TEXT"?O.childNodes.length===1&&O.childNodes[0].nodeType===3?t.push(O.childNodes[0].nodeValue):t.push(""):O&&t.push(Cfs(D,O))}return Q},X2=function(D){if(!D.V){let w=
new Lw$(D);
g.P(D,w);let Q=new g.fL(D);g.P(D,Q);D.V=new eVi(w,Q,D.player.X(),D.player.getVideoData(),D.logger,D.player,D.Va)}return D.V},b_A=function(D){var w=D.player.getVideoData();
if(w.FD){var Q=D.player.X().Ga.get(w.videoId);if(Q){var Y={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(t,O,n)=>{t=D.loadNumber;O=w.videoId;D.loaded&&D.loadNumber===t&&D.player.getVideoData().videoId===O&&(n=g.Kw(n)&&n.responseXML?n.responseXML:null)&&Wl(D,n)}};
g.p9()&&(Y.onFinish=Uuy(D,Y.onFinish));Y.postParams={ic_only:"1"};cii(Y,Q);D.ma=!0;g.mp(w.FD,Y)}}},T$m=function(D){var w=new g.B({Z:"div"});
g.wE(w.element,!1);var Q=new H_i(D.player,w.element,X2(D));g.P(Q,w);w.ZV(D.S.element);Q.Ta();return Q},Epx=function(D,w,Q,Y,t){if(!D.player.X().be){var O=[];
w.navigationEndpoint&&g.H(w.navigationEndpoint,g.yY)&&g.H(w.navigationEndpoint,g.yY).browseId&&O.push(new B3s("openUrl","click",new AQO(`/channel/${g.H(w.navigationEndpoint,g.yY).browseId}`,"new",!0,!0)));var n=w.watermark.thumbnails[0];Y={channel_name:w.channelName,end_ms:w.endTimeMs,image_height:n.height,image_type:1,image_url:n.url,image_width:n.width,is_mobile:!1,session_data:{annotation_id:Q,ei:t,feature:"iv",itct:w.trackingParams,src_vid:Y},start_ms:w.startTimeMs};if(w.subscribeButton&&g.H(w.subscribeButton,
g.JY)){Y.channel_id=g.H(w.subscribeButton,g.JY).channelId;w=g.H(w.subscribeButton,g.JY);n=t=null;w.subscribed?(w.subscriberCountWithUnsubscribeText&&(t=g.$4(w.subscriberCountWithUnsubscribeText)),w.subscriberCountText&&(n=g.$4(w.subscriberCountText))):(w.subscriberCountText&&(t=g.$4(w.subscriberCountText)),w.subscriberCountWithSubscribeText&&(n=g.$4(w.subscriberCountWithSubscribeText)));let X=g.H(w.signInEndpoint?.commandMetadata,g.MX)?.url||"";w={subscribeText:g.$4(w.unsubscribedButtonText),subscribeCount:t||
"",unsubscribeText:g.$4(w.subscribedButtonText),unsubscribeCount:n||"",enabled:w.enabled||!1,classic:!1,subscribed:w.subscribed||!1,feature:"iv",signInUrl:X};Y.standalone_subscribe_button_data=w}O=new dus(Q,"branding","branding",O,Y);Y=Fwi(D);D.player.A("web_player_overlay_positioned_layout")?(Y.setAttribute("data-overlay-order","11"),D.player.dD(Y,4,!0)):D.S.element.appendChild(Y);O=new i_m(Y,X2(D),O);O.Ta();g.P(O,O);D.C[Q]=O}};
g.lD.prototype.WM=g.YA(46,function(D,w){var Q=g.OQ(this.ek());Q&&Q.WM(D,w)});
var RB={},oB=null;g.KP(CQ,g.m4);g.K=CQ.prototype;g.K.getDuration=function(){return this.duration};
g.K.play=function(D){if(D||this.Y==0)this.progress=0,this.coords=this.S;else if(this.isPlaying())return!1;Fr(this);this.startTime=D=g.N8();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.j=this.startTime;this.progress||this.iY();this.Ox("play");this.isPaused()&&this.Ox("resume");this.Y=1;var w=g.CP(this);w in RB||(RB[w]=this);N3A();T3y(this,D);return!0};
g.K.stop=function(D){Fr(this);this.Y=0;D&&(this.progress=1);IIm(this,this.progress);this.onStop();this.Vv()};
g.K.pause=function(){this.isPlaying()&&(Fr(this),this.Y=-1,this.Ox("pause"))};
g.K.qp=function(){this.Y==0||this.stop(!1);this.Ox("destroy");CQ.jG.qp.call(this)};
g.K.destroy=function(){this.dispose()};
g.K.EV=function(){this.Ox("animate")};
g.K.Ox=function(D){this.dispatchEvent(new KZu(D,this))};
g.KP(KZu,g.fK);g.KP(uL,CQ);uL.prototype.D=function(){};
uL.prototype.EV=function(){this.D();uL.jG.EV.call(this)};
uL.prototype.Vv=function(){this.D();uL.jG.Vv.call(this)};
uL.prototype.iY=function(){this.D();uL.jG.iY.call(this)};
g.KP(qp,uL);qp.prototype.D=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var Lw$=class extends g.In{constructor(D){super();this.S=D||window;this.Y=[]}listen(D,w,Q,Y){Q=(0,g.ux)(Q,Y||this.S);D=g.jy(D,w,Q);this.Y.push(D);return D}HL(D,w,Q,Y){Q=(0,g.ux)(Q,Y||this.S);D=dJi(D,w,Q);this.Y.push(D);return D}kJ(D){g.zz(D);g.YY(this.Y,D)}removeAll(){g.zz(this.Y);this.Y.length=0}qp(){this.removeAll();super.qp()}};var AiV=class extends g.Uw{constructor(D){super(D);this.j=this.endscreen=null;this.S={};this.C={};this.G=this.D=null;this.V=[];this.Y=null;this.aN=!0;this.N=0;D=D.X();this.O=g.$g(D)||D.Ht==="profilepage";this.events=new g.J0(this);g.P(this,this.events);this.events.B(this.player,g.F1("creatorendscreen"),this.onCueRangeEnter);this.events.B(this.player,g.CS("creatorendscreen"),this.onCueRangeExit);this.events.B(this.player,"resize",this.YJ);this.events.B(window,"focus",this.ma);this.load();var w=g.WO("STYLE");
(g.mU("HEAD")[0]||document.body).appendChild(w);this.addOnDisposeCallback(()=>{g.fG(w)});
w.sheet&&(w.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),w.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!Tq(this)){var D=g.wY7(this.player.getVideoData());D?(D=Np(D,hFy(this)),IB(this,D,!1)):btP(this)}}unload(){IB(this,null);this.j&&(this.j.abort(),this.j=null);super.unload()}oK(D,w){return Tq(this)?D==="loadCustomEndscreenRenderer"?(D=Np(w,"new"),IB(this,D),!0):null:null}getOptions(){return Tq(this)?["loadCustomEndscreenRenderer"]:[]}YJ(){if(this.endscreen&&this.endscreen.elements){var D=this.player.getVideoContentRect();if(D&&D.width!==0&&D.height!==0){var w=this.player.getPlayerSize();
if(w&&w.width!==0&&w.height!==0){var Q=D.width/D.height;var Y=0;var t=-1;for(var O=0;O<jnV.length;O++){var n=Math.abs(w.width-jnV[O]);if(t===-1||Y>=n)t=O,Y=n}Y=zVM[t];this.D&&g.cO(this.D.element,"outline-width",Math.max(w.width,w.height)+"px");for(w=0;w<this.endscreen.elements.length;++w){O=this.endscreen.elements[w].id;t=this.S[O];n=this.C[O];if(!t||!n)continue;let W=n.width*Q/n.aspectRatio;var X=Math.round(n.width*D.width);O=Math.round(W*D.height);let v=D.left+Math.round(n.left*D.width),V=D.top+
Math.round(n.top*D.height);g.BO(t.element,X,O);g.jf(t.element,v,V);g.zd(t.element,snA);X>256||O>256?g.Hg(t.element,"ytp-ce-large-round"):X>96||O>96?g.Hg(t.element,"ytp-ce-medium-round"):g.Hg(t.element,"ytp-ce-small-round");g.zd(t.element,muA);X=n.left+n.width/2;n=n.top+W/2;g.Hg(t.element,X<=.5&&n<=.5?"ytp-ce-top-left-quad":X>.5&&n<=.5?"ytp-ce-top-right-quad":X<=.5&&n>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.zd(t.element,zVM);g.Hg(t.element,Y);(t=g.ko(document,"div","ytp-ce-expanding-overlay-body",
t.element)[0])&&g.cO(t,"height",`${O}px`)}}}}}onCueRangeEnter(D){if(this.endscreen)if(D.getId()==="ytp-ce-in-endscreen")rW(this,this.endscreen.impressionUrls),(D=g.fu())&&this.endscreen.visualElement&&g.ml(D,this.endscreen.visualElement),this.Y&&(g.Hg(this.Y,"ytp-ce-element-show"),this.Y.removeAttribute("aria-hidden"),this.player.EP()?g.Hg(this.Y,"ytp-ce-hide-button-lower"):g.jl(this.Y,"ytp-ce-hide-button-lower"));else{D=D.getId().substring(15);var w=this.S[D],Q=this.C[D];g.Hg(w.element,"ytp-ce-element-show");
w.element.removeAttribute("aria-hidden");w=this.player.getRootNode();g.Hg(w,"ytp-ce-shown");rW(this,Q.impressionUrls);(w=g.fu())&&g.ml(w,Q.visualElement);this.player.X().aN&&g.vA(this.player,"endscreenelementshown",D)}}onCueRangeExit(D){if(D.getId()==="ytp-ce-in-endscreen")this.Y&&(g.jl(this.Y,"ytp-ce-element-show"),this.Y.setAttribute("aria-hidden","true"));else{D=D.getId().substring(15);var w=this.S[D];g.jl(w.element,"ytp-ce-element-show");w.element.setAttribute("aria-hidden","true");w=this.player.getRootNode();
g.jl(w,"ytp-ce-shown");this.player.X().aN&&g.vA(this.player,"endscreenelementhidden",D)}}ma(D){D.target===window&&(new g.U5(()=>{for(let w of Object.values(this.S))g.zd(w.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}Eo(D){for(let w of Object.values(this.S))D?w.element.setAttribute("hidden",""):w.element.removeAttribute("hidden")}Q_(D){this.Y&&this.player.getRootNode().removeChild(this.Y);
D&&(g.Hg(D,"ytp-ce-hide-button-container"),this.Y=D,g.PA(this.player,this.Y,4))}},jnV=[346,426,470,506,570,640,853,1280,1920],zVM="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),muA=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],snA=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var AQO=class{constructor(D,w,Q,Y){this.value=D;this.target=w;this.showLinkIcon=Q;this.S=Y}Y(){return this.value?this.value:null}},mJm={NQ:"current",Cgt:"new"};var B3s=class{constructor(D,w,Q){this.type=D;this.trigger=w;this.url=Q}},kjx={CLOSE:"close",WCV:"openUrl",SUBSCRIBE:"subscribe"},Zt$={qQ:"click",CLOSE:"close",ptU:"hidden",htN:"rollOut",O2t:"rollOver",Twp:"shown"};var dus=class{constructor(D,w,Q,Y,t){this.id=D;this.type=w;this.style=Q;this.data=t;this.action=Y||[]}R7(){var D=wEx(this,w=>w.type==="openUrl"&&w.url!=null);
return D?D.url:null}},qsi={TR:"anchored",Mf:"branding",CHANNEL:"channel",Cb:"cta",Otp:"highlightText",fiK:"label",PLAYLIST:"playlist",POPUP:"popup",n3U:"speech",SUBSCRIBE:"subscribe",eit:"title",VIDEO:"video",YHp:"website"},ufx={Mf:"branding",P4:"card",kI:"drawer",h6K:"highlight",TjN:"marker",qul:"promotion",TEXT:"text",W_N:"widget"};var kHV=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
Z_A=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var B$s=class{constructor(D,w){this.context=D;this.Y=w}};var Ieu=class{constructor(D,w){this.merchant=D;this.price=w}};var D$V=class extends g.In{constructor(D,w){super();this.element=D;this.context=w;this.Uv=!1;this.Kt=new Map;this.kU=new Map;this.context.L.addEventListener(g.F1("annotations_module"),Q=>{(Q=this.Kt.get(Q))&&Q.apply(this)});
this.context.L.addEventListener(g.CS("annotations_module"),Q=>{(Q=this.kU.get(Q))&&Q.apply(this)})}addCueRange(D,w,Q,Y,t){D=new g.z1(D,w,{id:Q,
namespace:"annotations_module"});Y&&this.Kt.set(D,Y);t&&this.kU.set(D,t);this.context.L.HK([D],1)}Ta(){this.context.S.subscribe("resize",this.jQ,this)}Di(){return this.element}XL(D,w,Q,Y,t,O){if(this.Uv)return!1;O&&(O.stopPropagation(),O.preventDefault());this.navigate(D,Q,Y,t);return!1}show(){}hide(){}destroy(){g.fG(this.Di())}jQ(){}navigate(D,w,Q,Y){var t=D.Y();if(t){var O=t7P(t,D.target),n=()=>{D.S&&this.context.L.pauseVideo();var X=this.context.videoData.wx||!1,W=g.uN(t||"");X&&W&&(W.v||W.list)?
this.context.L.lZ(W.v,w,W.list,!1):g.k4(t||"",O==="current"?"_top":void 0,w)};
O==="new"&&(n(),n=null);n3(this.context.logger,Q,n,Y);Ysx(t)||(Q=g.fu(),Y=w.itct,Q&&Y&&g.Zu(Q,g.v3(Y)))}}qp(){this.Kt.clear();this.kU.clear();super.qp()}createElement(D){D=new g.B(D);g.P(this,D);return D.element}};var H_i=class extends D$V{constructor(D,w,Q){super(w,Q);this.L=D;this.eventId=null;this.Ry=this.Ga=this.Am=this.D=this.isInitialized=!1;this.cards=[];this.lK=this.V=this.yl=this.G=this.JN=this.Y=null;this.aN=[];this.ma=this.N=this.DF=this.bK=null;this.C=0;this.Ht=new g.U5(()=>{},Q.U.BD?4E3:3E3);
g.P(this,this.Ht);this.Ev=new g.U5(()=>{});
g.P(this,this.Ev);this.g$=new B$s(Q,(Y,t,O,n,X,W)=>{ma(this,Y,t,O,n,X,W)});
this.O=new g.B({Z:"div",J:"iv-drawer",W:{id:"iv-drawer"},K:[{Z:"div",J:"iv-drawer-header",W:{"aria-role":"heading"},K:[{Z:"span",J:"iv-drawer-header-text"},{Z:"button",uK:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{Z:"div",J:"iv-drawer-content"}]});g.P(this,this.O);this.j=this.O.element;this.Pt=new g.hN(this.O,330);g.P(this,this.Pt);this.Sk=g.Z_("iv-drawer-header-text",this.j);this.S=g.Z_("iv-drawer-content",this.j);this.addCueRange(0,Q.videoData.lengthSeconds*
1E3,"",()=>{this.Am&&BX(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.Am=this.D)&&wu(this)});
this.Np=new g.J0(this);g.P(this,this.Np);this.L.addEventListener("videodatachange",this.aM.bind(this))}aM(){this.ma&&D1(this,this.ma)}isAvailable(){var D;if(D=!!this.cards.length)(D=this.L.getRootNode())?(D=g.D9(D),D=173<D.width&&173<D.height):D=!1;return D}jQ(){var D=this.isAvailable();g.wE(this.Di(),D);g.s5(this.context.L.getRootNode(),g.tw.IV_DRAWER_ENABLED,D);Gq(this.L)}destroy(){this.L.WM(!1);try{this.L.getRootNode().removeChild(this.j)}catch(D){}g.m7(this.aN);this.Np.S();this.JN&&this.JN.dispose();
this.G&&this.G.dispose();super.destroy()}AO(){this.context.Y.listen(g.Z_("iv-drawer-close-button",this.j),"click",this.Bh,this);this.context.Y.listen(this.S,"touchend",()=>{this.Ht.start()});
this.context.Y.listen(this.S,"scroll",this.gj,this);this.context.S.subscribe("onHideControls",()=>{this.Ga=!0});
this.context.S.subscribe("onShowControls",()=>{this.Ga=!1});
this.context.S.subscribe("onVideoAreaChange",()=>{this.Ga=g.bQ(this.L.getRootNode(),"ytp-autohide")});
this.aN.push(g.sg("iv-button-shown",this.li,this));this.aN.push(g.sg("iv-button-hidden",this.Wh,this));Wws(this)}findLastIndex(D){if(this.cards.length===0)return 0;var w=g.kA(this.cards,Q=>D.tL.startMs>Q.tL.startMs||D.tL.startMs===Q.tL.startMs&&D.tL.timestamp>=Q.tL.timestamp?!0:!1);
return w===-1?0:w+1}Bh(){if(this.D){n3(this.context.logger,tX(this).dZ.close);var D=g.fu();D&&this.N&&g.Zu(D,this.N);wu(this)}}gj(){g.s5(this.j,"iv-drawer-scrolled",this.S.scrollTop>0)}li(){var D=g.fu(),w=tX(this);w=w?w.DF:this.DF;D&&w&&g.A9(D,[w])}Wh(){var D=g.fu(),w=tX(this);w=w?w.DF:this.DF;D&&w&&g.kl(D,[w])}mC(){var D=tX(this);n3(this.context.logger,D.dZ.B3);var w=g.fu();if(w&&D)if(this.L.A("web_infocards_teaser_show_logging_fix")){let Q=[];D.I6&&Q.push(D.I6);D.DF&&Q.push(D.DF);Q.length>0&&g.A9(w,
Q)}else g.A9(w,[D.I6,D.DF])}RD(){var D=g.fu(),w=tX(this);D&&w&&g.kl(D,[w.I6])}V2(D){var w=tX(this),Q=g.fu();this.Y?D?(D=this.context.logger,n3(D,w.dZ.nX),D.L.sendVideoStatsEngageEvent(4,void 0),Q&&w.I6&&g.Zu(Q,w.I6)):(D=this.context.logger,n3(D,w.dZ.nX),D.L.sendVideoStatsEngageEvent(4,void 0),Q&&w.DF&&g.Zu(Q,w.DF)):(D=this.context.logger,n3(D,w.dZ.nX),D.L.sendVideoStatsEngageEvent(4,void 0),Q&&this.DF&&g.Zu(Q,this.DF))}};var wF$=class extends D$V{constructor(D,w,Q){super(D,w);this.annotation=Q;this.isActive=!1}Ta(){super.Ta();pEA(this)}show(){super.show();var D=g.fu(),w=this.annotation.data;D&&w&&(w=w.session_data)&&g.A9(D,[g.v3(w.itct)])}hide(){super.hide();var D=g.fu(),w=this.annotation.data;D&&w&&(w=w.session_data)&&g.kl(D,[g.v3(w.itct)])}};var i_m=class extends wF${constructor(D,w,Q){super(D,w,Q);this.Y=null;this.S=!1}show(){if(!this.isActive){super.show();if(!this.S){g.Hg(this.Di(),"iv-branding");let D=this.annotation.data;this.Y=this.createElement({Z:"img",uK:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:D.image_url,width:D.image_width,height:D.image_height}});g.wE(this.Y,!1);let w=this.createElement({Z:"button",uK:["branding-img-container","ytp-button"]});w.appendChild(this.Y);this.Di().appendChild(w);
let Q=this.annotation.R7();Q&&ma(this,w,Q,this.annotation.id,D.session_data);this.S=!0}g.wE(this.Di(),!0);this.isActive=!0;if(this.Y){try{M7b(this,this.Y)}catch{}g.Hg(this.context.L.getRootNode(),"ytp-branding-shown");this.context.L.getRootNode().style.setProperty("--branding-image-width",`${this.Y.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.wE(this.Di(),!1),this.isActive=!1,g.jl(this.context.L.getRootNode(),"ytp-branding-shown"))}destroy(){g.jl(this.context.L.getRootNode(),
"ytp-branding-shown");super.destroy()}};var eVi=class{constructor(D,w,Q,Y,t,O,n){this.Y=D;this.D=w;this.U=Q;this.videoData=Y;this.logger=t;this.L=O;this.S=n}};var N$u=class extends wF${constructor(D,w,Q){super(D,w,Q);this.V=this.isCollapsed=this.O=!1;this.C=5E3;this.S=this.D=this.Y=this.j=null;this.N=this.createElement({Z:"div",uK:["iv-promo-contents"]});this.G=new g.U5(()=>{this.Y.setAttribute("aria-hidden","true");g.wE(this.D,!1);g.wE(this.S,!0)},700,this);
g.P(this,this.G)}show(){this.isActive||(super.show(),this.O||(GHb(this),this.O=!0),g.wE(this.Di(),!0),g.Zi(function(){g.jl(this.Di(),"iv-promo-inactive")},100,this),this.Di().removeAttribute("aria-hidden"),this.isActive=!0,$e(this),aey(this),gpu(this,this.C))}hide(){this.isActive&&(g.Hg(this.Di(),"iv-promo-inactive"),this.isActive=!1,this.Di().setAttribute("aria-hidden","true"))}XL(D,w,Q,Y,t,O){return this.isCollapsed?!1:super.XL(D,w,Q,Y,t,O)}Ht(D){this.V=!0;
OR(this,500,D)}g$(){this.V=!1;xuM(this)}aN(D){D.stopPropagation();this.hide()}ma(D){D.stopPropagation();$e(this);this.isCollapsed=!0;g.Hg(this.Di(),"iv-promo-collapsed-no-delay");this.G.start()}destroy(){this.G.dispose();super.destroy()}};var Qas=class{constructor(D){this.L=D}};g.BT("annotations_module",class extends g.Uw{constructor(D){super(D);this.aN=this.ma=!1;this.loadNumber=0;this.C={};this.logger=new Qas(this.player);this.G=new g.J0(this);this.N=this.j=null;this.events=new g.J0(this);this.VJ=this.V=this.Y=null;this.Ta=[];g.P(this,this.G);this.G.B(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.G.B(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.G.B(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.G.B(this.player,"resize",Q=>{this.publish("resize",Q)});
this.G.B(this.player,"presentingplayerstatechange",Q=>{this.publish("presentingplayerstatechange",Q)});
this.subscribe("presentingplayerstatechange",this.Ht,this);this.subscribe("resize",this.O,this);this.player.X().Ga.subscribe("vast_info_card_add",this.g$,this);g.P(this,this.events);this.jQ=this.createElement({Z:"div",J:"video-custom-annotations"});this.S=new g.B({Z:"div",uK:["ytp-player-content","ytp-iv-player-content"]});g.P(this,this.S);g.PA(this.player,this.S.element,4);this.S.hide();this.D=new g.B({Z:"div",uK:["ytp-iv-video-content"]});g.P(this,this.D);D=this.createElement({Z:"div",J:"video-annotations"});
D.appendChild(this.jQ);this.D.element.appendChild(D);this.c9()?this.load():this.player.A("web_fix_annotations")&&(this.j=()=>{this.loaded||this.Lt()||!this.c9()||(opi(this),this.load())},this.player.addEventListener("videodatachange",this.j));
var w=this.createElement({Z:"style"});(g.mU("HEAD")[0]||document.body).appendChild(w);this.addOnDisposeCallback(()=>{g.fG(w)});
if(D=w.sheet){for(let Q of kHV)D.insertRule(Q,0);for(let Q of Z_A)D.insertRule(Q,0)}}oK(D,w){if(!RVP(this.player.X().playerStyle))return null;switch(D){case "loadCustomAnnotationsXml":return(D=g.jX(w))&&Wl(this,D),!0;case "removeCustomAnnotationById":return w&&this.Y&&(kf(this.Y,w),Gq(this.player)),!0}return null}getOptions(){return RVP(this.player.X().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}c9(){var D=this.player.getVideoData(),w=D.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return D.wx||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.A("web_fix_annotations")?Kwu(this)?w?.isWatermarkEnforced===!0?!0:w?.isAnnotationsEnabled??!1:!1:Kwu(this)}O(){if(this.D){var D=this.player.xX().getVideoContentRect(!0);g.BO(this.D.element,D.width,D.height);g.jf(this.D.element,D.left,D.top)}if(this.Y){var w=this.player.qO();D=this.Y;w=w.width;g.s5(D.j,"iv-drawer-small",w<=426);g.s5(D.j,"iv-drawer-big",w>=1280)}}Ht(D){PfY(this,D.state);D.state.Y(2)&&(this.EP()&&this.Sv()&&this.player.getPresentingPlayerType()!==
2&&this.K7(!1),this.WM(!1))}load(){super.load();PfY(this,this.player.getPlayerStateObject());this.loadNumber++;var D=this.player.getVideoData();rim(this,D);g.PA(this.player,this.D.element,4);this.O();var w=g.hY(D),Q=D.XG();if(this.player.A("web_fix_annotations")){if(w&&(w.featuredChannel&&Epx(this,w.featuredChannel,w.annotationId||"branding",D.videoId||null,D.eventId||null),w=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,w?.isWatermarkEnforced&&!w?.isAnnotationsEnabled))return;
Q&&vl(this,Q)}else Q&&vl(this,Q),w&&w.featuredChannel&&Epx(this,w.featuredChannel,w.annotationId||"branding",D.videoId||null,D.eventId||null);this.VJ=g.Z_("ytp-cards-button",this.player.getRootNode());D.yL()&&hVA(this,D)}onVideoDataChange(){}unload(){this.player.C2("annotations_module");for(let D of Object.keys(this.C))this.C[D].destroy();this.V=null;this.Y&&(this.Y.destroy(),this.Y=null,Gq(this.player));this.ma=!1;this.N&&(this.N.abort(),this.N=null);this.aN=!1;this.C={};this.S.hide();super.unload();
this.D.detach();opi(this)}g$(D){D===this.player.getVideoData().videoId&&(this.loaded?b_A(this):this.load())}EP(){return this.Y?.isAvailable()||this.aN}Sv(){return!!this.Y&&this.Y.D}K7(D,w=!1,Q){this.EP();this.Y&&(D?Q?BX(this.Y,Q,w):BX(this.Y,"YOUTUBE_DRAWER_AUTO_OPEN",w):wu(this.Y))}WM(D,w){this.player.publish(D?"cardsteasershow":"cardsteaserhide",w)}qp(){this.player.X().Ga.unsubscribe("vast_info_card_add",this.g$,this);g.jl(this.player.getRootNode(),g.tw.IV_DRAWER_OPEN);var D=this.Ta,w=g.qr;for(let Q=
0,Y=D.length;Q<Y;Q++)w.Ja(D[Q]);this.Ta.length=0;super.qp()}createElement(D){D=new g.B(D);g.P(this,D);return D.element}});g.BT("creatorendscreen",AiV);})(_yt_player);
