(function(g){var window=this;'use strict';var tAA=async function(D,w,Q){D.S=g.mp(w,Q)},Vj=function(D){D.isActive()||D.start()},O0O=function(D,w){var Q=new g.XD;
Q.languageCode=D.languageCode;Q.languageName=D.languageName;Q.name=D.name;Q.displayName=D.displayName;Q.kind=D.kind;Q.isDefault=!1;Q.Y=D.Y;Q.isTranslateable=D.isTranslateable;Q.vssId=D.vssId;Q.url=D.url;Q.translationLanguage=w;D.xtags&&(Q.xtags=D.xtags);D.captionId&&(Q.captionId=D.captionId);return Q},Sj=function(D,w){return w?D.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},$$Y=function(D){return g.Jb(D)||D.A("web_enable_caption_language_preference_stickiness")},nvY=async function(D,w){D=
D+"|"+w;
w=await g.Og();if(!w)throw g.TV("gct");return(await g.so(w)).get("captions",D)},XFb=function(D,w,Q){nvY(D,w).then(Y=>{Y&&Q(Y.trackData,new g.XD(Y.metadata))})},l4=function(D){if(!Wry.test(D))throw Error("'"+D+"' is not a valid hex color");
D.length==4&&(D=D.replace(vvO,"#$1$1$2$2$3$3"));D=D.toLowerCase();D=parseInt(D.slice(1),16);return[D>>16,D>>8&255,D&255]},VAP=function(){var D={},w="suggest_correction"in g.og?g.og.suggest_correction:"Edit caption";
w=w||"";for(let Q in D){let Y=()=>String(D[Q]);
w=w.replace(new RegExp("\\$\\{"+Q+"\\}","gi"),Y);w=w.replace(new RegExp("\\$"+Q,"gi"),Y)}return w},f3=function(){return g.DC("yt-player-caption-display-settings")},Skb=function(D,w){var Q=g.yy(D.segments,w);
Q>=0||Q<0&&(-Q-1)%2===1||(Q=-Q-1,Q>0&&w-D.segments[Q-1]===1&&Q<D.segments.length&&D.segments[Q]-w===1?(g.Qy(D.segments,Q),g.Qy(D.segments,Q-1)):Q>0&&w-D.segments[Q-1]===1?D.segments[Q-1]=w:Q<D.segments.length&&D.segments[Q]-w===1?D.segments[Q]=w:(g.Si(D.segments,Q,0,w),g.Si(D.segments,Q+1,0,w)))},lEm=function(D){return D.Y&&D.Y.G?D.Y.G+D.player.pW()<D.player.getCurrentTime():!1},fEP=function(D,w){if(D.policy.AM&&D.player.aW()){var Q=g.Ey(w,D.policy,{});
Q.set("pot",D.player.aW());Q=Q.R7()}else Q=g.Ey(w,D.policy,{}).R7();var Y={format:"RAW",withCredentials:!0};if(D.policy.bK){Y.method="POST";let n=w.j;n&&Object.keys(n).length>0?Y.postBody=g.X4(n,g.Fw):Y.postBody=(0,g.T8)([120,0])}D.G&&(Y.responseType="arraybuffer");var t=++D.Ta,O=(0,g.z)();D.S=g.B5(Q,Y,3,100,-1,n=>{n.errorCode==="net.timeout"&&D.player.d$("capnt",{rn:t++})}).then(n=>{if(D.policy.QV&&t%100===1){var X=(0,g.z)();
D.player.d$("caprsp",{rn:t,ms:X-O,kb:(n.xhr.responseText.length/1024).toFixed()})}a:{n=n.xhr;D.Lt();if(D.D){var W=!(D.G?n.response:n.responseText)||n.status>=400;if(X=g.ZFP(n)){n=g.Ey(D.D,D.policy,{});D.D.HB(n,X);fEP(D,D.D);break a}W?D.player.d$("capfail",{status:n.status}):(g.oT("fcb_r",(0,g.z)(),D.player.getVideoData()?.le||""),X=D.D.dv[0],W=X.eQ,D.V!=null&&D.C!==W&&(D.G?D.V(n.response,(X.segmentStartTime+D.player.pW())*1E3):D.V(n.responseText,(X.segmentStartTime+D.player.pW())*1E3),D.C=W))}D.D=
null;D.S=null}}).h6(n=>{D.D=null;
D.S=null;D.player.d$("capfail",{rn:t,status:n.xhr?.status})});
D.D=w;Skb(D.j,D.D.dv[0].eQ)},yHV=function(D,w){return w!=null&&w in D.S.Y?D.S.Y[w]:null},JHV=function(D,w,Q){var Y=[];
for(let t in D.S.Y){if(!D.S.Y.hasOwnProperty(t))continue;let O=D.S.Y[t];if(g.QX(O,Q||null)){let n=O.info.captionTrack;n&&n.languageCode===w&&Y.push(O)}}return Y.length?Y[0]:null},pFO=function(D,w){var Q=[];
for(let t in D.S.Y){if(!D.S.Y.hasOwnProperty(t))continue;var Y=D.S.Y[t];if(g.QX(Y,w||null)){let O=Y.info.id,n=O,X=`.${O}`,W="",v="";if(Y=Y.info.captionTrack)O=Y.languageCode,n=Y.displayName,X=Y.vssId,W=Y.kind,v=Y.id;Q.push(new g.XD({id:t,languageCode:O,languageName:n,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:X,kind:W,captionId:v}))}}return Q},MAx=function(D,w,Q,Y){var t=w/360*16;
w>=D&&(D=640,Y>Q*1.3&&(D=480),t=Q/D*16);return t},aEu=function(D){var w=1+.25*(D.fontSizeIncrement||0);
if(D.offset===0||D.offset===2)w*=.8;return w},gvu=function(D,w){var Q="vertical-rl";
D.Y.xN===1&&(Q="vertical-lr");g.Z3&&(Q=Q==="vertical-lr"?"tb-lr":"tb-rl");g.cO(w,"-o-writing-mode",Q);g.cO(w,"-webkit-writing-mode",Q);g.cO(w,"writing-mode",Q);g.cO(w,"text-orientation","upright");g.Hg(w,"ytp-vertical-caption");D.S.params.DT===3&&(g.cO(w,"text-orientation",""),g.cO(w,"transform","rotate(180deg)"))},Gyb=function(D,w){var Q={},Y=w.background?w.background:D.Y.Zu.background;
if(w.backgroundOpacity!=null||w.background){var t=w.backgroundOpacity!=null?w.backgroundOpacity:D.Y.Zu.backgroundOpacity;Y=l4(Y);Q.background="rgba("+Y[0]+","+Y[1]+","+Y[2]+","+t+")";D.JN&&(Q["box-decoration-break"]="clone",Q["border-radius"]=`${D.Kt*.25}px`)}if(w.fontSizeIncrement!=null||w.offset!=null)Q["font-size"]=`${D.kU*aEu(w)}px`;D.experiments.IN("enable_player_captions_new_style_defaults")&&(Q["line-height"]="1.375");Y=1;t=w.color||D.Y.Zu.color;if(w.color||w.textOpacity!=null)t=l4(t),Y=w.textOpacity==
null?D.Y.Zu.textOpacity:w.textOpacity,t="rgba("+t[0]+","+t[1]+","+t[2]+","+Y+")",Q.color=t,Q.fill=t;var O=w.charEdgeStyle;O===0&&(O=void 0);if(O){t=`rgba(34, 34, 34, ${Y})`;let W=`rgba(204, 204, 204, ${Y})`;w.d0&&(W=t=w.d0);let v=D.kU/16/2,V=Math.max(v,1);var n=Math.max(2*v,1),X=Math.max(3*v,1);let y=Math.max(5*v,1);Y=[];switch(O){case 4:for(;X<=y;X+=v)Y.push(`${n}px ${n}px ${X}px ${t}`);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(O=V;O<=X;O+=n)Y.push(`${O}px ${O}px ${t}`);break;case 2:Y.push(`${V}px ${V}px ${W}`);
Y.push(`-${V}px -${V}px ${t}`);break;case 3:for(X=0;X<5;X++)Y.push(`0 0 ${n}px ${t}`)}Q["text-shadow"]=Y.join(", ")}t="";switch(w.fontFamily){case 1:t='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:t='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:t='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:t='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:t='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:t=g.JC()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:t='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}t&&(Q["font-family"]=t);t=w.offset;t==null&&(t=D.Y.Zu.offset);switch(t){case 0:Q["vertical-align"]="sub";break;case 2:Q["vertical-align"]="super"}w.fontFamily===7&&(Q["font-variant"]="small-caps");w.bold&&(Q["font-weight"]="bold");w.italic&&(Q["font-style"]="italic");w.underline&&
(Q["text-decoration"]="underline");w.LG&&(Q.visibility="hidden");w.uo===1&&D.j&&(Q["text-combine-upright"]="all",Q["text-orientation"]="mixed",t=g.xg||g.dt,D.S.params.DT===3?Q.transform=t?"rotate(90deg)":"rotate(180deg)":t&&(Q.transform="rotate(-90deg)"));if(w.textEmphasis===1||w.textEmphasis===2||w.textEmphasis===3||w.textEmphasis===4||w.textEmphasis===5)if(g.xg)Q["font-weight"]="bold";else switch(Q["text-emphasis-style"]="filled circle",Q["text-emphasis-color"]="currentcolor",Q["webkit-text-emphasis"]=
"filled circle",w.textEmphasis){case 4:case 3:Q["text-emphasis-position"]="under left";Q["webkit-text-emphasis-position"]="under left";break;case 5:case 2:Q["text-emphasis-position"]="over right",Q["webkit-text-emphasis-position"]="over right"}return Q},x$$=function(D,w){if(D.Pt&&w.length===0)return 0;
D=1;for(let Q=0;Q<w.length;Q++){let Y=w[Q];typeof Y.text==="string"&&(D+=Y.text.split("\n").length-1,Y.append||Q===0||D++)}return D},yj=function(D){D=D.split("px");
return D.length>0?(D=Number(D[0]))?D:0:0},Frx=function(D,w,Q){D.bK=D.bK||!!Q;
var Y={};Object.assign(Y,D.Y.Zu);Object.assign(Y,Q||w.Y);Object.assign(Y,D.Va.Zu);(Q=!D.G)&&Rss(D);var t=D.yl&&D.Ga&&g.bs(Y,D.Ga)?D.yl:ovb(D,Y),O=typeof w.text==="string",n=O?w.text.split("\n"):[w.text];for(let W=0;W<n.length;W++){var X=W>0||!w.append;let v=n[W];X&&!Q?(Rss(D),t=ovb(D,Y)):X&&Q&&(Q=!1);v&&(t.appendChild(O?g.vO(v):v),O||v.tagName!=="RUBY"||v.childElementCount!==4||g.xg||!g.ef(v.children[2],"text-emphasis")||(X=D.j?"padding-right":"padding-top",g.ef(v.children[2],"text-emphasis-position")&&
(X=D.j?"padding-left":"padding-bottom"),g.tM?g.cO(t,X,"1em"):g.cO(t,X,"0.5em")))}D.Ga=Y;D.yl=t;D.N.push(w)},Rss=function(D){if(D.G){var w=D.G;
if(D.JN){var Q=D.Y.textAlign;Q===0?(w=w.firstElementChild)&&g.cO(w,{"border-bottom-left-radius":"0"}):Q===1&&(w=w.lastElementChild)&&g.cO(w,{"border-bottom-right-radius":"0"})}}D.G=g.WO("SPAN");g.cO(D.G,{display:"block"});g.Hg(D.G,"caption-visual-line");D.D.appendChild(D.G)},ovb=function(D,w){var Q=g.WO("SPAN");
g.cO(Q,{display:"inline-block","white-space":"pre-wrap"});g.cO(Q,Gyb(D,w));Q.classList.add("ytp-caption-segment");D.G.appendChild(Q);D.JN&&D.D.children.length>1&&(D=D.Y.textAlign,D===0?Q.previousElementSibling||g.cO(Q,{"border-top-left-radius":"0"}):D===1&&g.cO(Q,{"border-top-right-radius":"0"}));Q.previousElementSibling&&(g.cO(Q.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.cO(Q,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return Q},
uKO=function(D,w,Q){if(D===255&&w===255||!D&&!w)return{R1:D,
Eq:w,result:0};D=C1$[D];w=C1$[w];if(D&128){var Y;if(Y=!(w&128))Y=w,Y=Q.K2()&&Q.Eq===Y;if(Y)return{R1:D,Eq:w,result:1}}else if(w&128&&1<=D&&D<=31)return{R1:D,Eq:w,result:2};return{R1:D,Eq:w,result:3}},d$P=function(D,w,Q,Y){w===255&&Q===255||!w&&!Q?(++D.D===45&&D.reset(),D.j.S.clear(),D.G.S.clear()):(D.D=0,qkV(D.j,w,Q,Y))},i0m=function(D,w){D.Y.sort((Q,Y)=>{var t=Q.time-Y.time;
return t===0?Q.order-Y.order:t});
for(let Q of D.Y)D.time=Q.time,Q.type===0?d$P(D,Q.Kx,Q.kL,w):Q.type===1&&D.S&496&&qkV(D.G,Q.Kx,Q.kL,w);D.Y.length=0},P1s=function(D,w){switch(D){case 0:return NnO[(w&127)-32];
case 1:return TnM[w&15];case 2:return IEx[w&31];case 3:return Krm[w&31]}return 0},JX=function(D,w){if(D.style.type===3){var Q=0,Y=0,t=D.G.time+0,O="",n="",X=t;
for(var W=1;W<=15;++W){var v=!1;for(var V=Y?Y:1;V<=32;++V){var y=D.D[W][V];if(y.Y!==0){Q===0&&(Q=W,Y=V);v=String.fromCharCode(y.Y);var J=y.timestamp;J<t&&(t=J);y.timestamp=X;n&&(O+=n,n="");O+=v;v=!0}if((y.Y===0||V===32)&&v){n="\n";break}else if(Y&&!v)break}if(Q&&!v)break}O&&w.j(Q,Y,t,X,O)}else for(Y=Q=0,O=t=D.G.time+0,n=1;n<=15;++n)for(X="",W=1;W<=32;++W)if(V=D.D[n][W],y=V.Y,y!==0&&(Q===0&&(Q=n,Y=W),v=String.fromCharCode(y),J=V.timestamp,J<=t&&(t=J),X+=v,V.reset()),W===32||y===0)X&&w.j(Q,Y,t,O,X),
t=O,X="",Y=Q=0},p3=function(D){return D.D[D.row][D.S]},ME=function(D,w,Q){w>=2&&D.S>1&&(--D.S,p3(D).Y=0);
var Y=p3(D);Y.timestamp=D.G.time+0;Y.Y=P1s(w,Q);D.S<32&&D.S++},U$i=function(D,w,Q,Y){for(let n=0;n<Y;n++)for(let X=0;X<=32;X++){var t=D.D[w+n][X],O=D.D[Q+n][X];
t.Y=O.Y;t.timestamp=O.timestamp}},a1=function(D,w,Q){for(let Y=0;Y<Q;Y++)for(let t=0;t<=32;t++)D.D[w+Y][t].reset()},gu=function(D){D.row=D.Y>0?D.Y:1;
D.S=1;a1(D,0,15)},cHy=function(D){D.style.set(1);
D.Y=D.j;D.Y.Y=0;D.Y.style=D.style;D.D.mode=1<<D.Y.j},GO=function(D,w,Q){var Y=D.S,t=!1;
switch(D.style.get()){case 4:case 1:case 2:D.style.get()===4&&Y.Y>0||(JX(Y,Q),gu(D.S),gu(D.j),Y.row=15,Y.Y=w,t=!0)}D.style.set(3);D.Y=Y;D.Y.style=D.style;D.D.mode=1<<Y.j;t?Y.S=1:Y.Y!==w&&(Y.Y>w?(JX(Y,Q),a1(Y,Y.row-Y.Y,w)):Y.row<w&&(w=Y.Y),Y.Y=w)},hsu=function(D){D.style.set(4);
D.Y=D.text;D.Y.style=D.style;D.D.mode=1<<D.Y.j},qkV=function(D,w,Q,Y){D.S.update();
w=uKO(w,Q,D.S);switch(w.result){case 0:return;case 1:case 2:return}var t=w.R1;w=w.Eq;if(32<=t||!t)D.Y.mode&D.Y.S&&(Q=t,Q&128&&(Q=127),w&128&&(w=127),D=D.j.Y,Q&96&&ME(D,0,Q),w&96&&ME(D,0,w),Q!==0&&w!==0&&D.style.type===3&&JX(D,Y));else if(t&16)a:if(!D.S.matches(t,w)&&(Q=D.S,Q.R1=t,Q.Eq=w,Q.state=2,Q=t&8?D.C:D.D,D.j=Q,D.Y.mode=1<<(D.G<<2)+(Q.G<<1)+(Q.style.type===4?1:0),(D.Y.mode|1<<(D.G<<2)+(Q.G<<1)+(Q.style.type!==4?1:0))&D.Y.S))if(w&64){Y=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(t&7)<<1|w>>5&1];
D=w&16?((w&14)>>1)*4:0;w=Q.Y;switch(Q.style.get()){case 4:Y=w.row;break;case 3:if(Y!==w.row){if(Y<w.Y&&(Y=w.Y,Y===w.row))break;var O=1+w.row-w.Y;let n=1+Y-w.Y;U$i(w,n,O,w.Y);Q=O;t=w.Y;n<O?(O=n+t-O,O>0&&(Q+=O,t-=O)):(O=O+t-n,O>0&&(t-=O));a1(w,Q,t)}}w.row=Y;w.S=D+1}else switch(t&7){case 1:switch(w&112){case 32:ME(Q.Y,0,32);break a;case 48:w===57?(Y=Q.Y,p3(Y).Y=0,Y.S<32&&Y.S++):ME(Q.Y,1,w&15)}break;case 2:w&32&&ME(Q.Y,2,w&31);break;case 3:w&32&&ME(Q.Y,3,w&31);break;case 4:case 5:if(32<=w&&w<=47)switch(w){case 32:cHy(Q);
break;case 33:Y=Q.Y;Y.S>1&&(--Y.S,p3(Y).Y=0);break;case 36:Y=Q.Y;D=p3(Y);for(w=0;w<=15;w++)for(Q=0;Q<=32;Q++)if(Y.D[w][Q]===D){for(;Q<=32;Q++)Y.D[w][Q].reset();break}break;case 37:GO(Q,2,Y);break;case 38:GO(Q,3,Y);break;case 39:GO(Q,4,Y);break;case 40:ME(Q.Y,0,32);break;case 41:Y=Q;Y.style.set(2);Y.Y=Y.S;Y.Y.Y=0;Y.Y.style=Y.style;Y.D.mode=1<<Y.Y.j;break;case 42:Y=Q;D=Y.text;D.Y=15;D.style.set(4);gu(D);hsu(Y);break;case 43:hsu(Q);break;case 44:D=Q;w=D.S;switch(D.style.get()){case 1:case 2:case 3:JX(w,
Y)}a1(w,0,15);break;case 45:b:{w=Q;D=w.Y;switch(w.style.get()){default:case 2:case 1:break b;case 4:if(D.row<15){++D.row;D.S=1;break b}break;case 3:}D.Y<2&&(D.Y=2,D.row<D.Y&&(D.row=D.Y));w=D.row-D.Y+1;JX(D,Y);U$i(D,w,w+1,D.Y-1);a1(D,D.row,1)}break;case 46:a1(Q.j,0,15);break;case 47:D=Q,JX(D.S,Y),D.j.updateTime(D.D.time+0),Y=D.j,D.j=D.S,D.S=Y,cHy(D)}break;case 7:switch(w){case 33:case 34:case 35:Y=Q.Y,(Y.S+=w&3)>32&&(Y.S=32)}}},Lrs=function(D,w,Q,Y,t,O,n){var X=O[0],W=n[X.getAttribute("p")];
if(W.AE===1){var v=O[1],V=O[2];O=O[3];X.getAttribute("t");v.getAttribute("t");V.getAttribute("t");O.getAttribute("t");X.getAttribute("p");v.getAttribute("p");O.getAttribute("p");n=n[V.getAttribute("p")];X=rHO(X.textContent,v.textContent,V.textContent,O.textContent,n);return new xe(D,w,t,Q,X,Y,W)}switch(W.AE){case 9:case 10:W.textEmphasis=1;break;case 11:W.textEmphasis=2;break;case 12:W.textEmphasis=3;break;case 13:W.textEmphasis=4;break;case 14:W.textEmphasis=5}return new xe(D,w,t,Q,X.textContent||
"",Y,W)},rHO=function(D,w,Q,Y,t){var O=g.JC(),n=O?g.WO("DIV"):g.WO("RUBY"),X=g.WO("SPAN");
X.textContent=D;n.appendChild(X);D=O?g.WO("DIV"):g.WO("RP");D.textContent=w;n.appendChild(D);w=O?g.WO("DIV"):g.WO("RT");w.textContent=Q;n.appendChild(w);Q=t.AE;if(Q===10||Q===11||Q===12||Q===13||Q===14)if(g.cO(w,"text-emphasis-style","filled circle"),g.cO(w,"text-emphasis-color","currentcolor"),g.cO(w,"webkit-text-emphasis","filled circle"),t.AE===11||t.AE===13)g.cO(w,"webkit-text-emphasis-position","under left"),g.cO(w,"text-emphasis-position","under left");Q=!0;if(t.AE===4||t.AE===7||t.AE===12||
t.AE===14)g.cO(n,"ruby-position","over"),g.cO(n,"-webkit-ruby-position","before");else if(t.AE===5||t.AE===6||t.AE===11||t.AE===13)g.cO(n,"ruby-position","under"),g.cO(n,"-webkit-ruby-position","after"),Q=!1;t=O?g.WO("DIV"):g.WO("RP");t.textContent=Y;n.appendChild(t);O&&(Y=Q,g.cO(n,{display:"inline-block",position:"relative"}),O=n.firstElementChild.nextElementSibling,g.cO(O,"display","none"),O=O.nextElementSibling,g.cO(O,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.cO(n.lastElementChild,"display","none"),Y?(g.cO(n,"padding-top","0.6em"),g.cO(O,"top","0")):(g.cO(n,"padding-bottom","0.6em"),g.cO(O,"bottom","0")));return n},esy=function(D){var w="_"+R1++;
return new o1(0,0x8000000000000,0,w,D)},F2=function(D,w){D=D.getAttribute(w);
if(D!=null)return Number(D)},C3=function(D,w){D=D.getAttribute(w);
if(D!=null)return D==="1"},u4=function(D,w){D=F2(D,w);
return D!==void 0?D:null},du=function(D,w){D=D.getAttribute(w);
if(D!=null)return qE.test(D),D},b0s=function(D,w){var Q={},Y=w.getAttribute("ws");
Object.assign(Q,Y?D.O[Y]:D.j);D=u4(w,"mh");D!=null&&(Q.OO=D);D=u4(w,"ju");D!=null&&(Q.textAlign=D);D=u4(w,"pd");D!=null&&(Q.DT=D);D=u4(w,"sd");D!=null&&(Q.xN=D);D=du(w,"wfc");D!=null&&(Q.windowColor=D);w=F2(w,"wfo");w!==void 0&&(Q.windowOpacity=w/255);return Q},H0O=function(D,w){var Q={},Y=w.getAttribute("wp");
Y&&Object.assign(Q,D.V[Y]);D=u4(w,"ap");D!=null&&(Q.Ij=D);D=F2(w,"cc");D!=null&&(Q.vW=D);D=F2(w,"ah");D!=null&&(Q.Li=D);D=F2(w,"rc");D!=null&&(Q.iZ=D);w=F2(w,"av");w!=null&&(Q.NO=w);return Q},EvA=function(D,w,Q,Y){var t={};
Object.assign(t,H0O(D,w));Object.assign(t,b0s(D,w));Y?g.bs(t,D.j)?(Y=D.G,t=D.j):Y="_"+R1++:Y=w.getAttribute("id")||"_"+R1++;D=F2(w,"t")+Q;w=F2(w,"d")||0x8000000000000;if(t.DT===2||t.DT===3)Q=t.iZ,t.iZ=t.vW,t.vW=Q;return new o1(D,w,0,Y,t)},i4=function(D){D=g.iP(Math.round(D),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-D.length)+D},jas=function(D,w,Q,Y,t){Y===0&&(Y=0x8000000000000);
var O={};w.wpWinPosId&&Object.assign(O,D.j.get(w.wpWinPosId));w.wsWinStyleId&&Object.assign(O,D.G.get(w.wsWinStyleId));D=w.rcRowCount;D!==void 0&&(O.iZ=D);w=w.ccColCount;w!==void 0&&(O.vW=w);if(O.DT===2||O.DT===3)w=O.iZ,O.iZ=O.vW,O.vW=w;return new o1(Q,Y,0,t,O)},NE=function(D){var w=D.byteOffset;
D.byteOffset+=1;return D.Y.getUint8(w)},TO=function(D){var w=D.byteOffset;
D.byteOffset+=4;return D.Y.getUint32(w)},m$P=function(D){if(typeof D==="string")return!1;
D=new zss(D,0);return saO(D)},saO=function(D){if(!(D.byteOffset<D.Y.byteLength)||TO(D)!==1380139777)return!1;
D.version=NE(D);if(D.version>1)return!1;NE(D);NE(D);NE(D);return!0},AHP=function(D,w){if(!w)return"";
D.j&&D.S.params.xN!==1&&(w*=-1);return`translate${D.j?"X":"Y"}(${w}px)`},kyi=function(D){D.Ht=Array.from(D.element.getElementsByClassName("caption-visual-line"));
for(var w=D.S.params.iZ,Q=0,Y=0,t=D.Ht.length-1;Q<w&&t>-1;){var O=D.Ht[t];Y+=D.j?O.offsetWidth:O.offsetHeight;Q++;t--}D.ma=Y;w=Math;Q=w.max;isNaN(D.jQ)&&((Y=D.Y.vW)?(t=g.WO("SPAN"),g.JM(t,"\u2013".repeat(Y)),g.cO(t,Gyb(D,D.Y.Zu)),D.D.appendChild(t),D.jQ=t.offsetWidth,D.D.removeChild(t)):D.jQ=0);Y=D.D;D.Ta=Q.call(w,D.jQ,D.Bh,(D.j?Y.offsetHeight:Y.offsetWidth)+1)},Z0u=function(D,w){kyi(D);
var Q=D.Ht.reduce((Y,t)=>(D.j?t.offsetWidth:t.offsetHeight)+Y,0);
Q=D.ma-Q;if(Q!==D.Np){let Y=Q>0&&D.Np===0,t=Q<D.Np;w||isNaN(Q)||Y||!t||(g.Hg(D.element,"ytp-rollup-mode"),D.B(D.element,"transitionend",D.Ev));g.cO(D.D,"transform",AHP(D,Q));D.Np=Q}kyi(D)},DxP=function(D,w,Q,Y){var {formatId:t,
eQ:O,startTimeMs:n,durationMs:X}=D.sI(w),W={formatId:t,startTimeMs:n,durationMs:X,KZ:O,EU:O},v=BnY(D.F_,W.startTimeMs),V=v>=0?D.F_[v]:null,y=V?V.startTimeMs+V.durationMs:0,J=W.startTimeMs+W.durationMs;!V||W.startTimeMs-y>D.j?D.F_.splice(v+1,0,W):(V.durationMs=Math.max(y,J)-V.startTimeMs,V.EU=Math.max(V.EU,W.EU));Y(D.F_);Y=g.Z4(w);D=D.G;Y=Y.buffer.slice(Y.byteOffset,Y.byteLength+Y.byteOffset);w=w.info.j;D.Ta?D.V==null?g.I6(D.logger,350058965,"Null loaded track meta data at captions data received"):
Q.bS(Y,D.V,w*1E3):g.I6(D.logger,350058965,"Null Representation at captions data received")},Y7M=function(D,w){D.S=(Q,Y)=>{if(D.L.X().experiments.IN("html5_sabr_live_support_subfragmented_captions"))(D.Y?D.Y=D.Y.G(Q):(D.Y=Q,wrP(D.Y)),D.Y)?Q.info.zq&&(Qmx(D.Y),DxP(D,D.Y,w,Y),D.Y=null):g.I6(D.logger,350058965,"Empty slice");
else if(Q.info.zq){var t=Q;if(D.wh.length>0){for(t=D.wh.shift();D.wh.length>0;)t=t?.G(D.wh.shift());t=t?.G(Q)}t?(wrP(t),Qmx(t),DxP(D,t,w,Y)):g.I6(D.logger,350058965,"Empty slice")}else D.wh.push(Q)};
D.L.addEventListener("sabrCaptionsDataLoaded",D.S)},BnY=function(D,w){D=g.yy(D,{startTimeMs:w},(Q,Y)=>Q.startTimeMs-Y.startTimeMs);
return D>=0?D:-D-2},wrP=function(D){try{var w=g.wj(D)*1E3}catch(Q){w=D.info.segmentStartTime*1E3}w<0&&(w=D.info.segmentStartTime*1E3);
D.info.segmentStartTime=w/1E3;D.info.j=w/1E3},Qmx=function(D){try{var w=g.bFi(D)*1E3}catch(Q){w=D.info.D*1E3}w<0&&(w=D.info.D*1E3);
D.info.D=w/1E3;D.info.N=w/1E3},tpm=function(D,w){if(!g.Qe8(D)||D.Y!=null&&g.wM(w,D.Y)&&D.Y.Y.rawcc!=null)return!1;
w=!!D.Y&&D.Y.isManifestless&&Object.values(D.Y.Y).some(Q=>g.QX(Q,"386"));
D=!!D.Y&&!D.Y.isManifestless&&g.pBx(D.Y);return w||D},OmY=function(D,w,Q){var Y=[];
for(let t in D.S.Y){if(!D.S.Y.hasOwnProperty(t))continue;let O=D.S.Y[t];if(g.QX(O,Q||null)){let n=O.info.captionTrack;n&&n.languageCode===w&&Y.push(O)}}return Y.length?Y[0]:null},$xy=function(D,w){var Q=[];
for(let t in D.S.Y){if(!D.S.Y.hasOwnProperty(t))continue;var Y=D.S.Y[t];if(g.QX(Y,w||null)){let O=Y.info.id,n=O,X=`.${O}`,W="",v="";if(Y=Y.info.captionTrack)O=Y.languageCode,n=Y.displayName,X=Y.vssId,W=Y.kind,v=Y.id;Q.push(new g.XD({id:t,languageCode:O,languageName:n,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:X,kind:W,captionId:v}))}}return Q},XrA=function(D){var w=nns.length;
if(D.byteLength<w)return!1;D=new Uint8Array(D,0,w);for(let Q=0;Q<w;Q++)if(nns[Q]!==D[Q])return!1;return!0},I1=function(D){D=D.split(":");
var w=0;for(let Q of D)w=w*60+Number(Q);return w*1E3},W8V=function(D,w,Q,Y){Y=Object.assign({OO:0},Y);
return new o1(D,w,Q,"_"+R1++,Y)},vnx=function(D,w,Q,Y,t,O,n,X,W){switch(n.tagName){case "b":X.bold=!0;
break;case "i":X.italic=!0;break;case "u":X.underline=!0}for(let V=0;V<n.childNodes.length;V++){var v=n.childNodes[V];if(v.nodeType===3)v=new xe(w,Q,Y,t.id,v.nodeValue,O||V>0,g.rV(X)?void 0:X),W.push(v),t.Y.push(v);else{let y={};Object.assign(y,X);vnx(D,w,Q,Y,t,!0,v,y,W)}}},S7y=function(D,w,Q){if(typeof w==="string"||m$P(w))return[{trackData:w,
Hu:Q}];if(typeof w==="string"&&w.substring(0,6)==="WEBVTT"||typeof w!=="string"&&XrA(w))return[{trackData:w,Hu:Q}];var Y=new DataView(w);if(Y.byteLength<=8||Y.getUint32(4)!==1718909296)return[];var t=g.kQU(Y);if(D.Oo&&t){var O=g.zg(t),n=g.sS(t);t=t.segmentNumber;O&&t&&D.Oo.NU(t,O,n)}D=g.t5(Y,1835295092);if(!D||!D.length||!D[0].size)return[];O=[];for(n=0;n<D.length;n++)t=D[n],t=new Uint8Array(w,t.dataOffset,t.size-(t.dataOffset-t.offset)),t=g.Ec(t),O.push({trackData:t,Hu:Q+n*1E3});VpA(Y,O,Q);return O=
O.filter(X=>!!X.trackData)},fTb=function(D,w,Q){D.Y||(D.Y=new lTy);
D=D.Y.D(w,Q);Math.random()<.01&&g.ou(Error("Deprecated subtitles format in web player: WebVTT"));return D},VpA=function(D,w,Q){var Y=g.BC(D,0,1836476516),t=9E4;
Y&&(t=g.D4(Y)||9E4);Y=0;var O=g.t5(D,1836019558);for(let X=0;X<O.length;X++){var n=O[X];X<w.length&&(n=g.BC(D,n.dataOffset,1953653094))&&(n=g.BC(D,n.dataOffset,1952867444))&&(n=g.YD(n)/t*1E3,X===0&&(Y=n),w[X].Hu=n-Y+Q||Q*X*1E3)}},yfb=function(D){var w={};
if(D=g.Sb(D))w.lang=D,g.qmi.test(D)&&(w.DT=1);return w},UR=function(D){return D.D==="HLS"&&D.Sk?!0:D.yl&&D.Sk&&D.D!=="LIVE"&&D.D!=="SABR_LIVE"},Jfm=function(D){return!D.j&&D.yl&&D.Pt&&(D.D==="LIVE"||D.D==="SABR_LIVE")},cl=function(D,w,Q=!1){var Y=D.U.A("enable_player_captions_new_style_defaults")?pri:MpA,t=Y.Zu;
D.G={};Object.assign(D.G,Y);D.G.Zu={};Object.assign(D.G.Zu,t);D.C={Zu:{}};var O=w.backgroundOverride?D.C:D.G,n=w.background||t.background;qE.test(n);O.Zu.background=n;O=w.colorOverride?D.C:D.G;n=w.color||t.color;qE.test(n);O.Zu.color=n;O=w.windowColorOverride?D.C:D.G;n=w.windowColor||Y.windowColor;qE.test(n);O.windowColor=n;O=w.backgroundOpacityOverride?D.C:D.G;n=w.backgroundOpacity;n==null&&(n=t.backgroundOpacity);O.Zu.backgroundOpacity=n;O=w.fontSizeIncrementOverride?D.C:D.G;n=w.fontSizeIncrement;
n==null&&(n=t.fontSizeIncrement);O.Zu.fontSizeIncrement=n;n=w.fontStyleOverride?D.C:D.G;O=w.fontStyle;O==null&&(O=t.bold&&t.italic?3:t.bold?1:t.italic?2:0);n=n.Zu;switch(O){case 1:n.bold=!0;delete n.italic;break;case 2:delete n.bold;n.italic=!0;break;case 3:n.bold=!0;n.italic=!0;break;default:delete n.bold,delete n.italic}O=w.textOpacityOverride?D.C:D.G;n=w.textOpacity;n==null&&(n=t.textOpacity);O.Zu.textOpacity=n;O=w.windowOpacityOverride?D.C:D.G;n=w.windowOpacity;n==null&&(n=Y.windowOpacity);O.windowOpacity=
n;Y=w.charEdgeStyleOverride?D.C:D.G;O=w.charEdgeStyle;O==null&&(O=t.charEdgeStyle);Y.Zu.charEdgeStyle=O;Y=w.fontFamilyOverride?D.C:D.G;O=w.fontFamily;O==null&&(O=t.fontFamily);Y.Zu.fontFamily=O;D.loaded&&D.lK();Q&&g.B1("yt-player-caption-display-settings",w,2592E3)},hX=function(D,w,Q){w&&!D.aN?(w=esy({DT:0,
lang:"en"}),D.aN=[w,new xe(w.start,w.end-w.start,0,w.id,Q??"Captions look like this")],D.player.HK(D.aN)):!w&&D.aN&&(aTY(D,D.aN),D.aN=null)},G3A=function(D){if(D.U.A("enable_player_captions_persistence_state_machine")){var w=g.DC("yt-player-caption-persistence");
if(w==null){let Q=g.$x().oN(65);if(Q===!0)w=!1;else{let Y=g.Jb(D.U)?ru(D):gn$(D);Y!=null?w=!!Y:Q===!1&&(w=!0)}w!==void 0&&L3(D,w)}return w}},ru=function(D){if(!D.L.isInline())return g.DC("yt-player-sticky-caption")},gn$=function(D){if(!D.storage)return null;
try{var w=D.storage.get("module-enabled")}catch(Q){D.storage.remove("module-enabled")}return w},ej=function(D){if(D.U.A("enable_player_captions_persistence_state_machine"))return G3A(D);
var w=void 0,Q=g.$x().oN(65);if(g.Jb(D.U)&&Q!=null){if(ru(D)!=null)return!1;w=!Q}return w},xxy=function(D){if(D.U.A$===1||D.videoData.fO===1||g.TD(D.videoData,"yt:cc")==="alwayson")return!0;
if(D.videoData.captionTracks.length)var w=D.getAudioTrack().S;if(D.U.A("enable_player_captions_persistence_state_machine")){var Q=G3A(D);if(Q!==void 0)return!!Q}else if(D.U.A$===2&&(g.Jb(D.U)?Q=ru(D):Q=gn$(D),Q!=null))return!!Q;Q=Sj(D.player.getAudioTrack(),g.Jb(D.U));var Y=g.TD(D.videoData,"yt:cc");if(ej(D)===void 0){if(Q==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return Y?Y==="on":!0;if(Q==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return Y==="on"}else return Y==="on";return w==="ON"||g.TD(D.videoData,
"yt:cc")==="on"},b4=function(D,w=!1){if(D.S&&!w||!D.videoData.captionTracks.length)return!1;
D=D.getAudioTrack();return!!D.Y||D.S==="FORCED_ON"},Rmy=function(D,w){if(D.S){var Q=D.L.OU().Di().textTracks,Y=null;
D.D==="HLS"?Y=D.S.getId():Y=D.S.toString();for(let O=0;O<Q.length;O++){var t=Q[O];t.id===Y&&(w?t.mode!=="showing"&&(t.mode="showing",t=D.S,D.TI(t,!!t,Hl(D)?"g":D.N?"m":"s")):t.mode==="showing"&&(t.mode="disabled"))}}},Hl=function(D){var w=ER(D);
return!!w&&D.S===w},onV=function(D,w){if(D.D==="HLS")return!1;
g.Li(D.videoData)&&(w=!0);w||(w=D.D==="TTS"?!1:D.D==="INNERTUBE"?!1:!0);return w||D.U.A("web_watch_disable_account_level_captions_settings")&&g.Jb(D.U)?!0:!!g.$x().oN(66)},ER=function(D){return D.O&&D.O.Y},jj=function(D,w){if(!D.Y)return null;
if(D.O&&D.O.j)return D.O.j;w=onV(D,w);w=g.IU(D.Y.Y,w);var Q=null;if($$Y(D.U)){var Y=D.L.isInline()?void 0:g.DC("yt-player-caption-sticky-language");var t=[Y,D.videoData.captionsLanguagePreference,D.U.captionsLanguagePreference,g.TD(D.videoData,"yt:cc_default_lang")];let X=!1;for(let W=0;W<t.length;W++){let v=t[W];if(v){X=!0;for(var O=0;O<w.length;O++)if(g.Sb(w[O])===v)return w[O];for(O=0;O<w.length;O++)if(g.Sb(w[O]).split("-")[0]===v.split("-")[0])return w[O]}}if(X&&D.Y&&(t=D.Y.O,t.length))for(var n of t)if(n.languageCode===
Y){Q=n;break}}else for(n=[D.videoData.captionsLanguagePreference,D.U.captionsLanguagePreference,g.TD(D.videoData,"yt:cc_default_lang")],Y=0;Y<n.length;Y++)for(t=0;t<w.length;t++)if(g.Sb(w[t])===n[Y])return w[t];n=null;D.O&&D.O.D&&(n=D.O.D);n||(n=w.find(X=>X.isDefault)||null);
n||(n=w[0]||ER(D));n&&Q&&g.Sb(n).split("-")[0]!==Q.languageCode.split("-")[0]&&(n=O0O(n,Q));return n},ke=function(D,w,Q){D.loaded&&D.unload();
Q!=null&&(D.N=Q,D.N&&(D.U.A("enable_player_captions_persistence_state_machine")?L3(D,!!w):g.Jb(D.U)?zO(D,!!w):sR(D,!!w)));w!==null||b4(D,!0)||D.TI(w,!!w,D.N?"m":"s");D.S=w;b4(D)&&(D.S=ER(D));AX(D,D.S??void 0);D.load()},L3=function(D,w){D.U.A("enable_player_captions_persistence_state_machine")&&g.B1("yt-player-caption-persistence",w,3122064E3)},zO=function(D,w){D.L.isInline()||g.B1("yt-player-sticky-caption",w,2592E3)},sR=function(D,w){if(D.storage)try{D.storage.set("module-enabled",w)}catch(Q){}},
AX=function(D,w){D.U.A("html5_modify_caption_vss_logging")&&(D.videoData.oH=w)},CUY=function(D,w){var Q=D.g$[w.id];
Q&&Q.S!==w&&(Q.dispose(),delete D.g$[w.id],Q=null);Q||(Q=F8i(D,w))&&(D.g$[w.id]=Q)},uFY=function(D,w){var Q=w.windowId;
D.JN[Q]||(D.JN[Q]=[]);D.JN[Q].push(w)},F8i=function(D,w){var Q=q7m(D);
if(!Q)return null;var Y=D.S?g.Sb(D.S):null;Y&&g.qmi.test(Y)&&(w.params.DT=1);var t=D.Ev.getPlayerSize();Y=t.height*D.Ta.height;t=t.width*D.Ta.width;D.U.playerStyle!=="google-live"||D.G.isDefault||Object.assign(w.params,D.G);switch(w.params.OO!=null?w.params.OO:w.Y.length>1?1:0){case 1:return new dxM(w,D.G,D.C,Q.width,Q.height,t,Y,D.U.experiments,D.Kt.bind(D),D.L);case 2:return new imV(w,D.G,D.C,Q.width,Q.height,t,Y,D.U.experiments,D.Kt.bind(D),D.L);default:return new Z1(w,D.G,D.C,Q.width,Q.height,
t,Y,D.U.experiments,D.Kt.bind(D),D.L)}},q7m=function(D){var w=D.Ev.getVideoContentRect(!0).height,Q=D.Ev.getVideoContentRect(!0).width;
if(!w||!Q)return null;w*=D.Ta.height;Q*=D.Ta.width;return{width:Q,height:w}},aTY=function(D,w){D.player.nn(w);
for(let Q of w)g.YY(D.jQ,Q);Vj(D.bK)},NqA=function(D,w){if(!D.Y)return{};
if(w){g.rV(w)||D.LY(w.vss_id,"m");if(D.j&&D.D!=="HLS"||!g.xA(w))return;if(g.rV(w)){ke(D,null,!0);return}let Y;var Q=g.IU(D.Y.Y,!0);for(let t=0;t<Q.length;t++){let O=Q[t];O.languageCode!==w.languageCode||Y&&(O.languageName!==w.languageName||(O.captionId||"")!==(w.captionId||"")||g.vC(O)!==w.displayName)||(Y=w.translationLanguage?O0O(O,w.translationLanguage):O)}D.C5(w.position);!Y||Y===D.S&&D.loaded||(w=g.Q0(),Q=g.Sb(Y),w.length&&Q===w[w.length-1]||(w.push(Q),g.B1("yt-player-caption-language-preferences",
w)),$$Y(D.U)&&!D.L.isInline()&&g.B1("yt-player-caption-sticky-language",Q,2592E3),ke(D,Y,!0))}else return D.loaded&&D.S&&!Hl(D)?g.V0(D.S):{};return""};
g.B4.prototype.NU=g.YA(72,function(D,w,Q){this.S.set(D,{NB:w,hd:Q})});
g.DO.prototype.NU=g.YA(71,function(D,w,Q){this.Ta.NU(D,w,Q)});
g.c4.prototype.ma=g.YA(70,function(){return!1});
g.c4.prototype.j=g.YA(69,function(){});
g.ho.prototype.j=g.YA(68,function(D,w,Q){this.Lt();w=this.C(D,w);var Y=this.iK.X().A("html5_report_captions_ctmp_qoe"),t=(0,g.z)();this.D();tAA(this,w,{format:"RAW",onSuccess:O=>{this.S=null;if(Y){var n=(O.responseText.length/1024).toFixed();let X=(0,g.z)();this.videoData.d$("capresp",{ms:X-t,kb:n})}n=O.getResponseHeader&&O.getResponseHeader("Content-Length")?Number(O.getResponseHeader("Content-Length")):0;Q.bS(O.responseText,D,void 0,void 0,n)},
onError:Y?O=>{this.videoData.d$("capfail",{status:O?.status??0})}:void 0,
withCredentials:!0})});
g.rL.prototype.j=g.YA(67,function(D,w,Q){this.Lt();w=this.C(D,w);this.D();this.S=g.mp(w,{format:"RAW",onSuccess:Y=>{this.S=null;var t=Y.getResponseHeader&&Y.getResponseHeader("Content-Length")?Number(Y.getResponseHeader("Content-Length")):0;Q.bS(Y.responseText,D,void 0,void 0,t)},
withCredentials:!0})});
g.JT.prototype.N=g.YA(66,function(){this.mediaElement.N()});
g.Sn.prototype.N=g.YA(65,function(){var D=g.ko(document,"track",void 0,this.Y);for(let w=0;w<D.length;w++)g.fG(D[w])});
g.JT.prototype.Np=g.YA(64,function(){return this.mediaElement.Np()});
g.Sn.prototype.Np=g.YA(63,function(){return!(!this.Y.textTracks||!this.Y.textTracks.addEventListener)});
g.JT.prototype.Ga=g.YA(62,function(){return this.mediaElement.Ga()});
g.Sn.prototype.Ga=g.YA(61,function(){return!!this.Y.textTracks});
g.JT.prototype.aN=g.YA(60,function(D){this.mediaElement.aN(D)});
g.Sn.prototype.aN=g.YA(59,function(D){for(let w=0;w<D.length;w++)this.Y.appendChild(D[w])});
g.lD.prototype.LY=g.YA(45,function(D,w){this.app.hN().LY(D,w)});
g.he.prototype.LY=g.YA(44,function(D,w){this.xU.LY(D,w)});
g.dL.prototype.LY=g.YA(43,function(D,w){D=[D,w];g.vD(this,g.l3(this.provider),"cfi",D)});
g.N2.prototype.LY=g.YA(42,function(D,w){this.qoe&&this.qoe.LY(D,w)});
g.jE.prototype.LY=g.YA(41,function(D,w){this.Ph.LY(D,w)});
g.mg.prototype.LY=g.YA(40,function(){});
g.cp.prototype.LY=g.YA(39,function(D,w){g.lw(this,37,[D,w])});
g.lD.prototype.TI=g.YA(38,function(D,w,Q){this.app.hN().TI(D,w,Q)});
g.he.prototype.TI=g.YA(37,function(D,w,Q){this.xU.TI(D,w,Q)});
g.dL.prototype.TI=g.YA(36,function(D,w,Q){if(this.yl!==D||this.Sk!==w)w=w==="rawcc"?"":w,Q=[D,w,this.yl,Q],g.vD(this,g.l3(this.provider),"cfs",Q),this.yl=D,this.Sk=w});
g.N2.prototype.TI=g.YA(35,function(D,w,Q){this.qoe&&this.qoe.TI(D,w,Q)});
g.jE.prototype.TI=g.YA(34,function(D,w,Q){this.Ph.TI(D,w,Q)});
g.mg.prototype.TI=g.YA(33,function(){});
g.cp.prototype.TI=g.YA(32,function(D,w,Q){g.lw(this,36,[D,w,Q])});
g.Dx.prototype.jE=g.YA(9,function(D){return(D=this.D(D))?D.Y:0});
g.YF.prototype.jE=g.YA(8,function(){return 0});
var vvO=/#(.)(.)(.)/,Wry=/^#(?:[0-9a-f]{3}){1,2}$/i,Tq$={en:"English"},ITb=class extends g.c4{constructor(D){super(D);this.S=new Set}G(D){var w=this.iK.OU();if(w&&w.Di()){w=w.Di().textTracks;for(let Q of w)Q.kind==="subtitles"&&!this.S.has(Q.language)&&Q.language&&(g.Db(this.Y,new g.XD({languageCode:Q.language,languageName:Q.language,kind:Q.kind,id:Q.id,displayName:Tq$[Q.label]||Q.label,vss_id:`.${Q.language}`})),this.S.add(Q.language))}g.IU(this.Y).length>0&&D.jA()}},K8u=class{constructor(){this.segments=
[]}contains(D){D=g.yy(this.segments,D);return D>=0||D<0&&(-D-1)%2===1}length(){return this.segments.length/2}},PUO=class extends g.In{constructor(D,w,Q,Y,t,O){super();this.policy=D;this.player=w;this.Ql=Q;this.V=Y;this.G=t;this.ma=O;this.j=new K8u;this.C=-1;this.S=this.D=this.Y=null;this.Ta=0;this.N=new g.U5(this.aN,1E3,this);this.events=new g.J0(this);g.P(this,this.N);g.P(this,this.events);this.events.B(w,"SEEK_COMPLETE",this.O);this.O();this.aN()}qp(){super.qp();this.S&&this.S.cancel()}O(){this.seekTo(this.player.getCurrentTime())}seekTo(D){D-=
this.player.pW();var w=this.Y;this.Y=g.rC(this.Ql.N(D).dv);w!==this.Y&&this.ma&&this.ma()}reset(){this.j=new K8u;this.C=-1;this.S&&(this.S.cancel(),this.S=null)}aN(){this.Lt();var D;if(D=this.Y!=null)D=this.Y,D=D.Ql.j(D);if(D&&!this.S&&!(this.Y&&this.Y.segmentStartTime-this.player.getCurrentTime()>30)){D=this.Y;D=D.Ql.yl(D);let t=D.dv[0];if(this.player.getVideoData()?.enableServerStitchedDai){var w=this.player.Za();if(w){var Q=t.Ql.info.id;let O=t.eQ;var Y=D.dv[0].j;if(this.policy.bK){if(w=g.lFi(w,
Y,O,Q,3))D.j=w}else if(Q=w.aB(Y,O,Q,3))if(Y=2,w.pC.has(O)?Y=0:g.cV(w,O)&&(Y=1),w=Y,w===0)Q&&(D.Y=new g.Ge(Q));else if(w===2){this.N.start();lEm(this)&&this.seekTo(this.player.getCurrentTime());return}}}t.Ql.index.gF(t.eQ)?(this.j.contains(D.dv[0].eQ)||fEP(this,D),this.Y=g.rC(D.dv)):lEm(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()}},Uxy=class extends g.c4{constructor(D,w){super(w);this.S=D;this.L=w;this.V=null;this.aN=!1;this.logger=new g.TK("caps");this.Ta=g.wM(this.L,this.S)}j(D,
w,Q){this.D();w=yHV(this,D.getId());w||(w=D.languageCode,w=this.S.isManifestless?JHV(this,w,"386"):JHV(this,w));if(w){var Y=(w.index.jE(w.index.Ux())-w.index.getStartTime(w.index.Ux()))*1E3,t=new g.LBP(this.L.X());this.V=new PUO(t,this.L,w,(O,n)=>{Q.bS(O,D,n,Y)},this.Ta||g.HG(w.info),()=>{this.V&&this.V.reset();
this.aN=!0})}}ma(){var D=this.aN;
this.aN=!1;return D}G(D){var w=this.L.X().A("html5_fallback_if_rawcc_missing");var Q=this.S.Y.rawcc!=null;if(!this.Ta||!Q&&w)w=this.S.isManifestless?pFO(this,"386"):pFO(this);else{if(!Q){g.I6(this.logger,386248249,"rawcc used but unavailable");return}w=[new g.XD({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.XD({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let Y of w)g.Db(this.Y,
Y);D.jA()}D(){this.V&&(this.V.dispose(),this.V=null)}C(){return""}},qE=/^#(?:[0-9a-f]{3}){1,2}$/i;var cfA=["left","right","center","justify"];var xe=class extends g.z1{constructor(D,w,Q,Y,t,O=!1,n=null){super(D,D+w,{priority:Q,namespace:"captions"});this.windowId=Y;this.text=t;this.append=O;this.Y=n}toString(){return super.toString()}};var Z1=class extends g.B{constructor(D,w,Q,Y,t,O,n,X,W,v){var V=v.isInline()&&!0,y={};Object.assign(y,w);Object.assign(y,D.params);Object.assign(y,Q);var J={};Object.assign(J,w.Zu);D.params.Zu&&Object.assign(J,D.params.Zu);Object.assign(J,Q.Zu);V&&(y.windowOpacity=.6,J.backgroundOpacity=0);y.Zu=J;var M=y.DT===1,R=[{Z:"span",J:"captions-text",W:{style:"word-wrap: normal; display: block;"}}],I=X.IN("caption_edit_on_hover")&&v.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
I&&R.unshift({Z:"button",J:"caption-edit",W:{tabindex:"0","aria-label":VAP()},K:[{Z:"svg",W:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},K:[{Z:"path",W:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({Z:"div",J:"caption-window",W:{id:`caption-window-${D.id}`,dir:M?"rtl":"ltr",tabindex:"0",lang:y.lang},K:R});this.experiments=
X;this.N=[];this.bK=!1;this.S=D;this.Ga=this.yl=null;this.oC=O;this.be=n;this.G=null;this.maxWidth=O*.96;this.maxHeight=n*.96;this.Y=y;this.Va=Q;this.g$=w;this.D=this.nt("captions-text");D=this.D.style;this.JN=X.IN("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in D||"WebkitBoxDecorationBreak"in D);this.kU=MAx(Y,t,O,n);this.z2=W;I&&(this.C=this.nt("caption-edit"),this.B(this.C,"click",()=>{this.z2()}));
this.type=0;this.Kt=this.kU*aEu(J);this.Am=V;this.Pt=X.IN("enable_centered_caption_for_tvfilm_video")&&v.getVideoData().isTvfilmVideo;this.O=v.X().r$().Y.oN(g.YYC);Y=new g.cN(this.element,!0);g.P(this,Y);Y.subscribe("dragstart",this.Pw,this);Y.subscribe("dragmove",this.ID,this);Y.subscribe("dragend",this.fL,this);this.lK=this.Uv=this.Ry=this.Sk=0;Y="";this.Y.windowOpacity&&(Y=l4(this.Y.windowColor),Y="rgba("+Y[0]+","+Y[1]+","+Y[2]+","+this.Y.windowOpacity+")");t={"background-color":Y,display:this.Y.isVisible===
!1?"none":"","text-align":cfA[this.Y.textAlign]};this.JN&&(t["border-radius"]=Y?`${this.Kt*.25}px`:"");(this.j=this.S.params.DT===2||this.S.params.DT===3)&&gvu(this,this.element);g.cO(this.element,t);V&&this.element.parentElement?.style.setProperty("--caption-window-color",Y);switch(this.Y.Ij){case 0:case 1:case 2:g.Hg(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Hg(this.element,"ytp-caption-window-bottom")}}Pw(D,w){this.Uv=D;this.lK=w;var Q=g.ZJ(this.element,this.element.parentElement);
this.Sk=D-Q.x;this.Ry=w-Q.y}ID(D,w){if(D!==this.Uv||w!==this.lK){g.bQ(this.element,"ytp-dragging")||g.Hg(this.element,"ytp-dragging");var Q=g.D9(this.element);D=D-this.Sk-.02*this.oC;var Y=w-this.Ry-.02*this.be,t=(D+Q.width/2)/this.maxWidth*3;t=Math.floor(g.iP(t,0,2));var O=(Y+Q.height/2)/this.maxHeight*3;O=Math.floor(g.iP(O,0,2));w=t+O*3;D=(D+t/2*Q.width)/this.maxWidth;D=g.iP(D,0,1)*100;Q=(Y+O/2*Q.height)/this.maxHeight;Q=g.iP(Q,0,1)*100;this.S.params.Ij=w;this.S.params.NO=Q;this.S.params.Li=D;this.S.params.isDefault=
!1;this.Y.Ij=w;this.Y.NO=Q;this.Y.Li=D;this.Y.isDefault=!1;this.g$.Ij=w;this.g$.NO=Q;this.g$.Li=D;this.g$.isDefault=!1;this.Wh()}}fL(){g.jl(this.element,"ytp-dragging")}Wh(){this.V(this.N)}V(D){var w=this.Am?0:Math.min(this.mC(),this.maxWidth),Q=this.V2(),Y=this.Am;if(Y){var t=getComputedStyle(this.D.parentNode);t=yj(t.borderLeftWidth)+yj(t.borderRightWidth)+yj(t.paddingLeft)+yj(t.paddingRight)}else t=0;var O=t;t="";this.S.params.DT===3&&(t="rotate(180deg)");var n=Y?`calc(96% - ${O}px)`:"96%";g.cO(this.element,
{top:0,left:0,right:"",bottom:"",width:w?`${w}px`:"",height:Q?`${Q}px`:"","max-width":n,"max-height":n,margin:"",transform:""});this.XL(D);t={transform:t,top:"",left:"",width:w?`${w}px`:"",height:Q?`${Q}px`:"","max-width":"","max-height":""};n=this.Y.Ij;var X=this.Y.Li,W=this.Y.NO;this.Pt&&n!=null&&(X=50,n=Math.floor(n/3)*3+1);X=X*.96+2;switch(n){case 0:case 3:case 6:(Y=this.Y.Zu.fontSizeIncrement)&&Y>0&&this.Y.DT!==2&&this.Y.DT!==3&&(X=Math.max(X/(1+Y*2),2));t.left=`${X}%`;break;case 1:case 4:case 7:t.left=
`${X}%`;X=0;this.O||(X=this.D.offsetWidth);w||X?(w=w||X+1,t.width=`${w}px`,t["margin-left"]=Y?`${w/-2-O/2}px`:`${w/-2}px`):(this.O&&(t.width="max-content"),t.transform+=" translateX(-50%)");break;case 2:case 5:case 8:t.right=`${100-X}%`}Y=W*.96+2;switch(n){case 0:case 1:case 2:t.top=`${Y}%`;break;case 3:case 4:case 5:t.top=`${Y}%`;Y=0;this.O||(Y=this.element.clientHeight);(Q=Q||Y)?(t.height=`${Q}px`,t["margin-top"]=`${Q/-2}px`):t.transform+=" translateY(-50%)";break;case 6:case 7:case 8:t.bottom=
`${100-Y}%`}g.cO(this.element,t);this.C&&(this.O?Q=this.Kt:(D=x$$(this,D),Q=this.Pt?D>0?this.D.offsetHeight/D:0:this.D.offsetHeight/D),this.C.style.height=`${Q}px`,this.C.style.width=`${Q}px`,this.element.style.paddingLeft=`${Q+5}px`,this.element.style.paddingRight=`${Q+5}px`,this.O||(D=Number(this.element.style.marginLeft.replace("px",""))-Q-5,Q=Number(this.element.style.marginRight.replace("px",""))-Q-5,this.element.style.marginLeft=`${D}px`,this.element.style.marginRight=`${Q}px`))}XL(D){if(this.type===
0&&this.S.params.iZ!==void 0&&this.experiments.IN("web_enable_popon_asr_captions")){var w=D,Q=this.S.params.iZ;if(w.length===0||Q<=0)D=[];else{D=[];for(let t=w.length-1;t>=0;t--){var Y=w[t];D.unshift(Y);let O=x$$(this,D);if(O>Q){D.shift();typeof Y.text==="string"&&(w=Y.text.split("\n"),Q=O-Q,w.length-Q>0&&(Q=w.slice(Q),Y=new xe(Y.start,Y.end-Y.start,Y.priority||0,Y.windowId,Q.join("\n"),Y.append,Y.Y),D.unshift(Y)));break}}}}for(Y=0;Y<D.length&&D[Y]===this.N[Y];Y++);if(this.bK||this.N.length>Y)Y=0,
this.bK=!1,this.N=[],this.G=this.Ga=this.yl=null,g.Sf(this.D);for(;Y<D.length;Y++)Frx(this,D[Y])}mC(){return 0}V2(){return 0}toString(){return super.toString()}};var rfs=class{constructor(){this.D=this.time=this.mode=this.S=0;this.j=new hmP(this);this.G=new hmP(this);this.Y=[];this.clear()}clear(){this.D=this.time=this.mode=0;this.Y=[];this.reset()}reset(){this.mode=0;this.j.reset(0);this.G.reset(1)}},C1$=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],L8Y=class{constructor(){this.type=0}set(D){this.type=D}get(){return this.type}},emP=class{constructor(){this.state=this.Eq=this.R1=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}K2(){return this.state!==0}matches(D,w){return this.K2()&&D===this.R1&&w===this.Eq}},bmy=class{constructor(){this.timestamp=this.Y=0}reset(){this.timestamp=
this.Y=0}},Bl=class{constructor(D){this.G=D;this.D=[];this.Y=this.S=this.row=0;this.style=new L8Y;this.j=0;for(D=0;D<=15;D++){this.D[D]=[];for(let w=0;w<=32;w++)this.D[D][w]=new bmy}}updateTime(D){for(let w=1;w<=15;++w)for(let Q=1;Q<=32;++Q)this.D[w][Q].timestamp=D}debugString(){var D="\n";for(let w=1;w<=15;++w){for(let Q=1;Q<=32;++Q){let Y=this.D[w][Q];D=Y.Y===0?D+"_":D+String.fromCharCode(Y.Y)}D+="\n"}return D}reset(D){for(let w=0;w<=15;w++)for(let Q=0;Q<=32;Q++)this.D[w][Q].reset();this.j=D;this.Y=
0;this.S=this.row=1}},NnO=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],TnM=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],IEx=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],Krm=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],HmP=class{constructor(D){this.D=D;this.G=0;this.style=new L8Y;this.C=new Bl(this.D);this.N=new Bl(this.D);this.text=new Bl(this.D);this.S=this.C;this.j=this.N;this.Y=this.S}reset(D,w){this.G=w;this.style.set(2);this.S=this.C;this.j=this.N;this.Y=this.S;var Q=(D<<2)+(w<<1);this.C.reset(Q);this.N.reset(Q);this.text.reset((D<<
2)+(w<<1)+1)}},hmP=class{constructor(D){this.Y=D;this.G=0;this.D=new HmP(this.Y);this.C=new HmP(this.Y);this.S=new emP;this.j=this.D}reset(D){this.G=D;this.S.clear();this.j=this.D;this.D.reset(D,0);this.C.reset(D,1)}};var EnY=class{j(){}};var Df=class extends g.In{reset(){}};var o1=class extends g.z1{constructor(D,w,Q,Y,t){super(D,D+w,{priority:Q,namespace:"captions"});this.id=Y;this.params=t;this.Y=[]}toString(){return super.toString()}},R1=0;var jmy=class extends Df{constructor(D){super();this.j=D;this.pens={};this.V={};this.O={};this.G="_"+R1++;this.N={};this.S=this.Y=null;this.C=!0}reset(){this.N={};this.S=this.Y=null;this.C=!0}D(D,w){D=D.firstChild;D.getAttribute("format");w=w||0;Number.isFinite(w);D=Array.from(D.childNodes);for(var Q of D)if(Q.nodeType===1)switch(Q.tagName){case "head":var Y=Q;break;case "body":var t=Q}if(Y){Y=Array.from(Y.childNodes);for(var O of Y)if(O.nodeType===1)switch(O.tagName){case "pen":Q=O.getAttribute("id");
Y=this.pens;D={};var n=O.getAttribute("p");n&&Object.assign(D,this.pens[n]);n=C3(O,"b");n!=null&&(D.bold=n);n=C3(O,"i");n!=null&&(D.italic=n);n=C3(O,"u");n!=null&&(D.underline=n);n=u4(O,"et");n!=null&&(D.charEdgeStyle=n);n=u4(O,"of");n!=null&&(D.offset=n);n=du(O,"bc");n!=null&&(D.background=n);n=du(O,"ec");n!=null&&(D.d0=n);n=du(O,"fc");n!=null&&(D.color=n);n=u4(O,"fs");n!=null&&n!==0&&(D.fontFamily=n);n=F2(O,"sz");n!==void 0&&(D.fontSizeIncrement=n/100-1);n=F2(O,"bo");n!==void 0&&(D.backgroundOpacity=
n/255);n=F2(O,"fo");n!==void 0&&(D.textOpacity=n/255);n=u4(O,"rb");n!=null&&n!==10&&n!==0&&(D.AE=n>10?n-1:n);n=u4(O,"hg");n!=null&&(D.uo=n);Y[Q]=D;break;case "ws":Y=O.getAttribute("id");this.O[Y]=b0s(this,O);break;case "wp":Y=O.getAttribute("id"),this.V[Y]=H0O(this,O)}}if(t){O=[];t=Array.from(t.childNodes);for(I of t)if(I.nodeType===1)switch(I.tagName){case "w":this.Y=EvA(this,I,w,!1);(t=this.N[this.Y.id])&&t.end>this.Y.start&&(t.end=this.Y.start);this.N[this.Y.id]=this.Y;O.push(this.Y);break;case "p":var X=
I;D=w;t=[];Y=X.getAttribute("w")||this.G;Q=!!C3(X,"a");D=(F2(X,"t")||0)+D;n=F2(X,"d")||5E3;Q||(!this.C&&this.S&&this.S.windowId===Y&&this.S.end>D&&(this.S.end=D),this.S&&this.S.text==="\n"&&(this.S.text=""));let c=Q?6:5;var W=X.getAttribute("p");W=W?this.pens[W]:null;let h=Array.from(X.childNodes);h.length&&(this.C=X.getAttribute("d")!=null);for(X=0;X<h.length;X++){var v=h[X],V=void 0;X>0&&(Q=!0);let L;v.nodeType===1&&(L=v);if(L&&L.tagName==="s"){if((v=(v=L.getAttribute("p"))?this.pens[v]:null)&&
v.AE&&(v.AE===1?(v=h.slice(X,X+4),v.length===4&&(V=Lrs(D,n,Y,Q,c,v,this.pens),X+=3)):V=Lrs(D,n,Y,Q,c,[L],this.pens)),!V){var y=L;V=D;v=n;var J=Y,M=Q;let b=y.textContent?y.textContent:"";var R=y.getAttribute("p");R=R?this.pens[R]:null;y=F2(y,"t")||0;V=new xe(V+y,v-y,c,J,b,M,R)}}else V=new xe(D,n,c,Y,v.textContent||"",Q,W);t.push(V);this.S=V}if(t.length>0){t[0].windowId===this.G&&(this.Y=EvA(this,I,w,!0),O.push(this.Y));for(let L of t)L.windowId=this.Y.id,this.Y.Y.push(L),O.push(L)}}var I=O}else I=
[];return I}};var zmV=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),sms=class extends Df{constructor(D){super();this.C=D;this.Y=new Map;this.j=new Map;this.G=new Map;this.S=new Map}reset(){this.S.clear()}D(D,w){D=JSON.parse(D);if(!D)return[];if(D.pens){var Q=D.pens,Y=0;for(var t of Q){Q={};var O=t.pParentId;O&&Object.assign(Q,this.Y.get(O));t.bAttr&&(Q.bold=!0);t.iAttr&&(Q.italic=!0);t.uAttr&&(Q.underline=!0);O=t.ofOffset;O!=null&&(Q.offset=O);t.szPenSize!==void 0&&(Q.fontSizeIncrement=t.szPenSize/100-1);
O=t.etEdgeType;O!=null&&(Q.charEdgeStyle=O);t.ecEdgeColor!==void 0&&(Q.d0=i4(t.ecEdgeColor));O=t.fsFontStyle;O!=null&&O!==0&&(Q.fontFamily=O);t.fcForeColor!==void 0&&(Q.color=i4(t.fcForeColor));t.foForeAlpha!==void 0&&(Q.textOpacity=t.foForeAlpha/255);t.bcBackColor!==void 0&&(Q.background=i4(t.bcBackColor));t.boBackAlpha!==void 0&&(Q.backgroundOpacity=t.boBackAlpha/255);(O=t.rbRuby)&&O!==10&&(Q.AE=O>10?O-1:O,Q.textEmphasis=zmV.get(Q.AE));t.hgHorizGroup&&(Q.uo=t.hgHorizGroup);this.Y.set(Y++,Q)}}if(D.wsWinStyles){Y=
D.wsWinStyles;t=0;for(var n of Y)Y={},(Q=n.wsParentId)?Object.assign(Y,this.G.get(Q)):Object.assign(Y,this.C),n.mhModeHint!==void 0&&(Y.OO=n.mhModeHint),n.juJustifCode!==void 0&&(Y.textAlign=n.juJustifCode),n.pdPrintDir!==void 0&&(Y.DT=n.pdPrintDir),n.sdScrollDir!==void 0&&(Y.xN=n.sdScrollDir),n.wfcWinFillColor!==void 0&&(Y.windowColor=i4(n.wfcWinFillColor)),n.wfoWinFillAlpha!==void 0&&(Y.windowOpacity=n.wfoWinFillAlpha/255),this.G.set(t++,Y)}if(D.wpWinPositions){t=D.wpWinPositions;n=0;for(var X of t)t=
{},(Y=X.wpParentId)&&Object.assign(t,this.j.get(Y)),X.ahHorPos!==void 0&&(t.Li=X.ahHorPos),X.apPoint!==void 0&&(t.Ij=X.apPoint),X.avVerPos!==void 0&&(t.NO=X.avVerPos),X.ccCols!==void 0&&(t.vW=X.ccCols),X.rcRows!==void 0&&(t.iZ=X.rcRows),this.j.set(n++,t)}if(D.events){D=D.events;X=[];for(let A of D)if(n=(A.tStartMs||0)+w,t=A.dDurationMs||0,A.id)Y=String(A.id),D=jas(this,A,n,t,Y),X.push(D),this.S.set(Y,D);else{A.wWinId?Y=A.wWinId.toString():(Y="_"+R1++,D=jas(this,A,n,t,Y),X.push(D),this.S.set(Y,D));
D=X;var W=A;t===0&&(t=5E3);Q=this.S.get(Y);let Qi=(O=!!W.aAppend)?6:5,ah=W.segs,Fx=null;W.pPenId&&(Fx=this.Y.get(W.pPenId));for(W=0;W<ah.length;W++){var v=ah[W],V=v.utf8;if(V){var y=v.tOffsetMs||0;let oh=null;v.pPenId&&(oh=this.Y.get(v.pPenId));if((Q.params.OO!=null?Q.params.OO:Q.Y.length>1?1:0)===2&&O&&V==="\n")continue;v=null;var J=[],M;if(M=oh&&oh.AE===1)a:{M=ah;var R=W;if(R+3>=M.length||!M[R+1].pPenId||!M[R+2].pPenId||!M[R+3].pPenId){M=!1;break a}var I=M[R+1].pPenId;(I=this.Y.get(I))&&I.AE&&I.AE===
2?(I=M[R+2].pPenId,I=this.Y.get(I),!I||!I.AE||I.AE<3?M=!1:(I=M[R+3].pPenId,M=(I=this.Y.get(I))&&I.AE&&I.AE===2?!0:!1)):M=!1}if(M)y=ah[W+1].utf8,v=ah[W+3].utf8,M=ah[W+2].utf8,R=this.Y.get(ah[W+2].pPenId),V=rHO(V,y,M,v,R),v=new xe(n,t,Qi,Y,V,O,oh),W+=3;else{if(V.indexOf("<")>-1){J=oh;M=Fx;R=n;I=t;var c=y,h=Qi,L=O;let H7=[];var b=g.jX(`<html>${V}</html>`);if(!b.getElementsByTagName("parsererror").length&&b.firstChild?.childNodes.length)for(let ZP of b.firstChild.childNodes){b=ZP.textContent?.replace(/\n/g,
"")??"";if(ZP.nodeType===3&&(!b||b.match(/^ *$/)!=null))continue;let W0={};Object.assign(W0,J||M);switch(ZP?.tagName){case "b":W0.bold=!0;break;case "i":W0.italic=!0;break;case "u":W0.underline=!0}H7.push(new xe(R+c,I-c,h,Q.id,b,L,W0))}J=H7}J.length||(J=[new xe(n+y,t-y,Qi,Q.id,V,O,oh||Fx)])}if(J.length)for(let H7 of J)D.push(H7),Q.Y.push(H7);else v&&(D.push(v),Q.Y.push(v))}O=!0}}w=X}else w=[];return w}};var mxy=class extends g.c4{constructor(D,w,Q){super(D);this.videoData=w;this.audioTrack=Q;this.O=w.xA}j(D,w,Q){XFb(this.videoData.videoId,D.vssId,Q.bS)}G(D){if(this.audioTrack)for(let w of this.audioTrack.captionTracks)g.Db(this.Y,w);D.jA()}};var dxM=class extends Z1{constructor(D,w,Q,Y,t,O,n,X,W,v){super(D,w,Q,Y,t,O,n,X,W,v);this.type=1}XL(D){var w=this.S.Y;super.XL(D);for(D=D.length;D<w.length;D++){let t=w[D],O;if(Y&&t.Y===Q)O=Y;else{O={};Object.assign(O,t.Y);Object.assign(O,AfP);var Q=t.Y;var Y=O}Frx(this,t,O)}}},AfP={LG:!0};var zss=class extends EnY{constructor(D,w){super();this.trackData=D;this.C=w;this.version=this.G=this.D=this.byteOffset=0;this.S=[];this.Y=new DataView(this.trackData)}j(D,w,Q,Y,t){if(Q<Y){let O="_"+R1++;Q=Q/1E3-this.C;Y=Y/1E3-this.C;D=new o1(Q,Y-Q,5,O,{textAlign:0,Ij:0,Li:w*2.5,NO:D*5.33});t=new xe(Q,Y-Q,5,O,t);this.S.push(D);this.S.push(t)}}},k3V=class extends Df{constructor(D,w){super();this.S=D;this.j=w;this.track=this.j.languageName==="CC3"?4:0;this.Y=new rfs;this.Y.S=1<<this.track}D(D){D=new zss(D,
this.S);if(saO(D)){for(;D.byteOffset<D.Y.byteLength;)for(D.version===0?D.D=TO(D)*(1E3/45):D.version===1&&(D.D=TO(D)*4294967296+TO(D)),D.G=NE(D);D.G>0;D.G--){var w=NE(D);let Q=NE(D),Y=NE(D);w&4&&(w&3)===this.track&&(this.track===0||this.track===1)&&(w=this.Y,w.Y.push({time:D.D,type:this.track,Kx:Q,kL:Y,order:w.Y.length}))}i0m(this.Y,D);return D.S}return[]}reset(){this.Y.clear()}};var imV=class extends Z1{constructor(D,w,Q,Y,t,O,n,X,W,v){super(D,w,Q,Y,t,O,n,X,W,v);this.type=2;this.Ht=[];this.Ta=this.ma=this.Np=0;this.jQ=NaN;this.Bh=0;this.RD=null;this.li=new g.U5(this.Ev,433,this);this.C&&(v.createClientVe(this.C,this,167342),this.B(this.C,"click",()=>{v.logClick(this.C)}),D=new g.cN(this.element,!0),g.P(this,D),D.subscribe("hoverstart",()=>{v.logVisibility(this.C,!0)},this));
g.Hg(this.element,"ytp-caption-window-rollup");g.P(this,this.li);g.cO(this.element,"overflow","hidden")}Wh(){g.h_(this.li)}Ev(){this.element.removeEventListener("transitionend",this.Ev,!1);g.jl(this.element,"ytp-rollup-mode");this.V(this.RD,!0)}V2(){return this.j?this.Ta:this.ma}mC(){return this.j?this.ma:this.Ta}V(D,w){this.RD=D;if(this.S.params.iZ){var Q=0;for(let Y=0;Y<this.N.length&&Q<D.length;Y++)this.N[Y]===D[Q]&&Q++;Q>0&&Q<D.length&&(D=this.N.concat(D.slice(Q)));this.Bh=this.Ta;this.ma=this.Ta=
0;super.V(D);Z0u(this,w)}super.V(D)}};var Zmy=class{constructor(D,w,Q,Y){this.L=D;this.G=w;this.logger=Q;this.jk=Y;this.F_=[];this.Y=null;this.D=[];this.wh=[];this.S=null;this.xJ={pOp:()=>this.S,
B5:()=>this.F_,
tNl:t=>{this.D=t},
IUv:()=>this.D};
D=g.mf(this.L.X().experiments,"html5_override_micro_discontinuities_threshold_ms");this.j=D>0?D:10}unload(){this.S!=null&&(this.L.removeEventListener("sabrCaptionsDataLoaded",this.S),this.S=null);this.F_=[];this.Y=null;this.D=[];this.L.publish("sabrCaptionsBufferedRangesUpdated",this.F_)}sI(D){return{formatId:g.jD(D.info.Ql.info,this.jk),eQ:D.info.eQ+(this.jk?0:1),startTimeMs:D.info.j*1E3,durationMs:D.info.N*1E3}}};var BqV=class extends g.c4{constructor(D,w){super(w);this.S=D;this.L=w;this.logger=new g.TK("caps");this.V=this.Ta=null;this.aN=new Zmy(this.L,this,this.logger,this.S.jk)}j(D,w,Q){this.D();w=D.getId();w=w!=null&&w in this.S.Y?this.S.Y[w]:null;w||(w=D.languageCode,w=this.S.isManifestless?OmY(this,w,"386"):OmY(this,w));w&&(this.V=D,this.Ta=w,Y7M(this.aN,Q),this.L.publish("sabrCaptionsTrackChanged",g.jD(w.info,this.S.jk)))}G(D){var w=this.S.isManifestless?$xy(this,"386"):$xy(this);for(let Q of w)g.Db(this.Y,
Q);D.jA()}D(){this.V&&(this.V=this.Ta=null,this.aN.unload(),this.L.publish("sabrCaptionsTrackChanged",null))}C(){return""}};var nns="WEBVTT".split("").map(D=>D.charCodeAt(0)),lTy=class extends Df{constructor(){super()}D(D,w){D instanceof ArrayBuffer&&(D=g.Ec(new Uint8Array(D)));
var Q=[];D=D.split(DFs);for(let R=1;R<D.length;R++){var Y=D[R],t=w;if(Y!==""&&!wUx.test(Y)){var O=wy.exec(Y);if(O&&O.length>=4){var n=I1(O[1]),X=I1(O[2])-n;n+=t;var W=(O=O[3])?O.split(" "):[];O={};var v=null;var V="";var y=null,J="";for(let I of W){W=I.split(":");if(W.length!==2)continue;var M=W[1];switch(W[0]){case "line":W=M.split(",");W[0].endsWith("%")&&(v=W[0],O.NO=Number.parseInt(v,10),W.length===2&&(V=W[1].trim()));break;case "position":W=M.split(",");y=W[0];O.Li=Number.parseInt(y,10);W.length===
2&&(J=W[1].trim());break;case "align":switch(M){case "start":O.textAlign=0;break;case "middle":O.textAlign=2;break;case "end":O.textAlign=1}}}v||V||(V="end");if(!y)switch(O.textAlign){case 0:O.Li=0;break;case 1:O.Li=100;break;case 2:O.Li=50}if(O.textAlign!=null){v=0;switch(V){case "center":v+=3;break;case "end":v+=6;break;default:v+=0}switch(J){case "line-left":v+=0;break;case "center":v+=1;break;case "line-right":v+=2;break;default:switch(O.textAlign){case 0:v+=0;break;case 2:v+=1;break;case 1:v+=
2}}V=v<0||v>8?7:v;O.Ij=V}Y=Y.substring(wy.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");J=O;O={};if(Y.indexOf("<")<0&&Y.indexOf("&")<0)t=W8V(n,X,5,J),n=new xe(n,X,5,t.id,Y,!1,g.rV(O)?void 0:O),Q.push(t),Q.push(n),t.Y.push(n);else for(V=Y.split(QMi),V.length===1?(Y=5,J=W8V(n,X,Y,J)):(v=Y=6,J=Object.assign({vW:32},J),J=new o1(n,X,v,"_"+R1++,J)),Q.push(J),v=n,y=0;y<V.length;y++)if(W=V[y],y%2===0){M=g.jX(`<html>${W}</html>`);let I;M.getElementsByTagName("parsererror").length?(I=M.createElement("span"),
I.appendChild(M.createTextNode(W))):I=M.firstChild;vnx(this,v,X-(v-n),Y,J,y>0,I,O,Q)}else v=I1(W)+t}wy.lastIndex=0}}return Q}},wUx=/^NOTE/,DFs=/(?:\r\n|\r|\n){2,}/,wy=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),QMi=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var YTi=class extends g.In{constructor(D,w){super();this.L=D;this.U=w;this.Y=null;this.Oo=this.L.Za();this.logger=new g.TK("caps")}clear(){this.Y&&this.Y.dispose();this.Y=null}reset(){this.Y&&this.Y.reset()}qp(){super.qp();this.clear()}};var MpA={windowColor:"#080808",windowOpacity:0,textAlign:2,Ij:7,Li:50,NO:100,isDefault:!0,Zu:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},pri={windowColor:"#080808",windowOpacity:0,textAlign:0,Ij:7,Li:50,NO:100,isDefault:!0,Zu:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.BT("captions",class extends g.Uw{constructor(D){super(D);this.L=D;this.jQ=[];this.g$={};this.JN={};this.N=!1;this.D="NONE";this.Y=this.O=this.aN=this.Np=this.kU=null;this.Uv={jA:()=>{this.jA()},
bS:(Y,t,O,n,X=0)=>{var W=Number(this.videoData.X().r$().Y.oN(g.y7n)??0);X>0&&W>0&&this.videoData.lengthSeconds>0&&X/this.videoData.lengthSeconds>W?this.L.d$("tts",{dropcap:X}):this.bS(Y,t,O,n)}};
this.S=null;this.U=this.L.X();this.videoData=this.L.getVideoData();this.Ev=this.L.xX();this.G={Zu:{}};this.C={Zu:{}};this.videoData.Am()?this.D="OFFLINE":g.ay7(this.videoData,this.L)?this.D="HLS":tpm(this.videoData,this.L)?this.D="SABR_LIVE":g.g2i(this.videoData,this.L)?this.D="LIVE":this.videoData.captionTracks.length?this.D="INNERTUBE":this.videoData.Kt&&(this.D="TTS");this.yl=this.U.controlsType==="3";this.XL=new YTi(this.L,this.U);this.Ht=new g.J0(this);this.V=new g.B({Z:"div",J:"ytp-caption-window-container",
W:{id:"ytp-caption-window-container"}});this.Ta={top:0,right:0,bottom:0,left:0,width:1,height:1};var w=null,Q=g.aw("yt-html5-player-modules::subtitlesModuleData");Q&&(w=new g.vm(Q));this.storage=w;w=D.OU();this.Sk=!!w?.Ga();this.Pt=!!w?.Np();this.j=UR(this);this.ma=Jfm(this);g.P(this,this.XL);this.j?this.Ga=this.bK=null:(this.bK=new g.Pg(this.Am,void 0,this),g.P(this,this.bK),this.Ga=new g.U5(this.Wh,2E3,this),g.P(this,this.Ga));g.P(this,this.Ht);g.PA(this.player,this.V.element,4);g.P(this,this.V);
this.j||this.Ht.B(D,"resize",this.lK);w=g.Oo(this.U)&&!g.ey()&&!this.L.isFullscreen();Q=this.U.r$().Y.oN(g.LuP)&&g.mA(this.U)&&g.DA;(this.Ry=(w||Q)&&!this.j&&!this.ma)&&this.Ht.B(D,w?"resize":"fullscreentoggled",this.mC);this.Ht.B(D,"onPlaybackAudioChange",this.V2);this.Ht.B(D,g.F1("captions"),Y=>{this.onCueRangeEnter(Y)});
this.Ht.B(D,g.CS("captions"),Y=>{this.onCueRangeExit(Y)});
cl(this,f3()||{});g.fA(this.player,"onCaptionsModuleAvailable");this.D==="HLS"&&this.j&&(D=this.L.OU().Di(),this.Pt&&this.Ht.B(D.textTracks,"addtrack",this.Bh))}qp(){if(this.j||this.ma){let D=this.L.OU();D&&!D.Lt()&&D.N()}else hX(this,!1);super.qp()}Ch(){return this.U.A("html5_honor_caption_availabilities_in_audio_track")&&this.D!=="LIVE"&&this.D!=="SABR_LIVE"}c9(){if(this.yl)return this.j||this.ma;if(this.D==="HLS")return this.j;var D=this.getAudioTrack();if(this.Ch()){if(!D.captionTracks.length)return!1;
if(!this.Y)return!0}D=Sj(D,g.Jb(this.U));return D==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:D==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?b4(this):ej(this)||b4(this)?!0:xxy(this)}load(){super.load();this.O=this.getAudioTrack();if(this.Y)this.S&&(this.XL.clear(),this.j?Rmy(this,!0):this.player.getPresentingPlayerType()!==3&&this.Y.j(this.S,"json3",this.Uv),this.D!=="HLS"&&this.j||this.ma||Hl(this)||g.fA(this.player,"captionschanged",g.V0(this.S)));else{let D;this.D==="OFFLINE"?D=new mxy(this.player,this.videoData,
this.getAudioTrack()):this.D==="SABR_LIVE"?D=new BqV(this.videoData.Y,this.player):this.D==="HLS"?D=new ITb(this.player):this.D==="LIVE"?D=new Uxy(this.videoData.Y,this.player):this.D==="INNERTUBE"?D=new g.ho(this.player,this.videoData,this.getAudioTrack()):D=new g.rL(this.player,this.videoData.Kt,this.videoData.videoId,g.O5P(this.videoData),this.videoData.VL,this.videoData.eventId);this.Y=D;g.P(this,this.Y);this.Y.G(this.Uv)}}unload(){this.j&&this.S?Rmy(this,!1):(this.Ga&&this.Ga.Ke(),this.player.C2("captions"),
this.jQ=[],this.Y&&this.Y.D(),this.XL.clear(),this.aN&&this.player.HK(this.aN),this.lK());super.unload();this.player.EM();g.fA(this.player,"captionschanged",{})}create(){this.c9()&&this.load();var D;a:{if(this.U.A("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(D=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let w of D)if(w.kind==="asr"&&w.languageCode===
"en"){D=!0;break a}D=!1}D&&this.L.publish("showpromotooltip",this.V.element)}jA(){var D=Sj(this.player.getAudioTrack(),g.Jb(this.U));var w=D==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?jj(this,this.N):D==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&b4(this)?ER(this):ej(this)||this.N||xxy(this)?jj(this,this.N):b4(this)?ER(this):null;if(this.D!=="HLS"&&this.j||this.ma){let Q=g.IU(this.Y.Y,!0);D=[];for(let Y=0;Y<Q.length;Y++){let t=Q[Y],O=g.WO("TRACK");O.setAttribute("kind","subtitles");O.setAttribute("label",
g.vC(t));O.setAttribute("srclang",g.Sb(t));O.setAttribute("id",t.toString());this.ma||O.setAttribute("src",this.Y.C(t,"vtt"));t===w&&O.setAttribute("default","1");D.push(O)}w=this.L.OU();w.aN(D);D=w.Di();this.Pt&&this.Ht.B(D.textTracks,"change",this.gj)}else!this.S&&w&&ke(this,w),g.fA(this.player,"onCaptionsTrackListChanged"),g.yo(this.player,"onApiChange")}getTrackById(D){var w=g.IU(this.Y.Y,!0);for(let Q=0;Q<w.length;Q++)if(w[Q].toString()===D)return w[Q];return null}gj(){var D=this.L.OU().Di().textTracks,
w=null;for(let Q=0;Q<D.length;Q++)D[Q].mode==="showing"&&(w=this.getTrackById(D[Q].id));(this.loaded?this.S:null)!==w&&ke(this,w,!0)}Bh(){this.Y?.G(this.Uv)}mf(){!this.S&&this.j||this.unload()}bS(D,w,Q,Y){if(D){AX(this,this.S??void 0);this.Y.ma()&&(this.jQ=[],this.L.C2("captions"),Vj(this.bK),this.XL.reset());a:{var t=this.XL;Y=Y||0;Q=S7y(t,D,Q||0);D=[];try{for(let h of Q){let L=h.trackData,b=h.Hu,A=t.U.A("safari_live_drm_captions_fix");if(typeof L!=="string"){Q=D;var O=Q.concat;if(A&&XrA(L))var n=
fTb(t,L,b);else{var X=t,W=w,v=L,V=b,y=Y;if(!m$P(v))throw Error("Invalid binary caption track data");X.Y||(X.Y=new k3V(y,W));n=X.Y.D(v,V)}var J=O.call(Q,n)}else{if(L.substring(0,6)==="WEBVTT")var M=D.concat(fTb(t,L,b));else{Q=D;var R=Q.concat;b:{W=t;X=w;if(L[0]==="{")try{W.Y||(W.Y=new sms(yfb(X)));var I=W.Y.D(L,b);break b}catch(Fx){g.xl(Fx);I=[];break b}let Qi=g.jX(L);if(!Qi||!Qi.firstChild){let Fx=Error("Invalid caption track data");Fx.params=L;throw Fx;}if(Qi.firstChild.tagName==="timedtext"){if(Number(Qi.firstChild.getAttribute("format"))===
3){v=Qi;W.Y||(W.Y=new jmy(yfb(X)));I=W.Y.D(v,b);break b}let Fx=Error("Unsupported subtitles format in web player (Format2)");Fx.params=L;throw Fx;}if(Qi.firstChild.tagName==="transcript"){let Fx=Error("Unsupported subtitles format in web player (Format1)");Fx.params=L;throw Fx;}let ah=Error("Invalid caption track data");ah.params=L;throw ah;}M=R.call(Q,I)}J=M}D=J}var c=D;break a}catch(h){g.I6(t.logger,187101178,`Captions parsing failed: ${h.message}. `);t.clear();c=[];break a}c=void 0}this.U.A("html5_sabr_live_support_subfragmented_captions")&&
this.Y instanceof BqV&&(w=this.Y.aN,t=[],c.length>0&&(t=c.slice(w.D.length)),w.D=!w.Y||w.Y.info.zq?[]:c,c=t);c.length>0&&(w=this.S,this.TI(w,!!w,Hl(this)?"g":this.N?"m":"s"));this.player.HK(c,void 0,this.D==="LIVE"||this.D==="SABR_LIVE");!this.N||this.ma||Hl(this)||g.YO(this.U)||g.tb(this.U)||g.En(this.U)||this.U.Ht==="shortspage"||this.player.isInline()||(this.Ga.Ke(),c=esy({Ij:0,Li:5,NO:5,iZ:2,textAlign:0,DT:0,lang:"en"}),this.Np=[c],w=["Click "," for settings"],this.kU||(t=new g.Tr(g.RL()),g.P(this,
t),this.kU=t.element),t=c.end-c.start,(J=g.vC(this.S))&&this.Np.push(new xe(c.start,t,0,c.id,J)),this.Np.push(new xe(c.start,t,0,c.id,w[0]),new xe(c.start,t,0,c.id,this.kU,!0),new xe(c.start,t,0,c.id,w[1],!0)),this.player.HK(this.Np),g.cg(this.Ga));!this.N||this.ma||Hl(this)||(this.U.A("enable_player_captions_persistence_state_machine")?L3(this,!0):g.Jb(this.U)?zO(this,!0):sR(this,!0),this.O&&(this.O.j=this.S),this.player.EM());this.N=!1}}onCueRangeEnter(D){this.jQ.push(D);Vj(this.bK)}onCueRangeExit(D){g.YY(this.jQ,
D);this.Y instanceof Uxy&&this.Y.Ta&&this.player.nn([D]);Vj(this.bK)}getCaptionWindowContainerId(){return this.V.element.id}Wh(){aTY(this,this.Np);this.Np=null}Am(){if(!this.Ry||!this.j){this.bK.stop();g.Lb(this.JN);this.jQ.sort(g.ov);var D=this.jQ;if(this.aN){let w=g.bx(D,function(Q){return this.aN.indexOf(Q)===-1},this);
w.length&&(D=w)}for(let w of D)w instanceof o1?CUY(this,w):uFY(this,w);for(let [w,Q]of Object.entries(this.g$)){let Y=w,t=Q;this.JN[Y]?(t.element.parentNode||(t instanceof imV||t instanceof dxM||g.us(this.g$,(O,n)=>{n!==Y&&O.S.params.Ij===t.S.params.Ij&&O.S.params.Li===t.S.params.Li&&O.S.params.NO===t.S.params.NO&&(O.dispose(),delete this.g$[n]);return n===Y},this),this.V.element.appendChild(t.element)),t.V(this.JN[Y])):(t.dispose(),delete this.g$[Y])}}}mQ(){cl(this,{},!0);
g.fA(this.player,"captionssettingschanged")}qZ(){var D=this.U.A("enable_player_captions_new_style_defaults")?pri:MpA,w=D.Zu;D={background:w.background,backgroundOpacity:w.backgroundOpacity,charEdgeStyle:w.charEdgeStyle,color:w.color,fontFamily:w.fontFamily,fontSizeIncrement:w.fontSizeIncrement,fontStyle:w.bold&&w.italic?3:w.bold?1:w.italic?2:0,textOpacity:w.textOpacity,windowColor:D.windowColor,windowOpacity:D.windowOpacity};w=f3()||{};w.background!=null&&(D.background=w.background);w.backgroundOverride!=
null&&(D.backgroundOverride=w.backgroundOverride);w.backgroundOpacity!=null&&(D.backgroundOpacity=w.backgroundOpacity);w.backgroundOpacityOverride!=null&&(D.backgroundOpacityOverride=w.backgroundOpacityOverride);w.charEdgeStyle!=null&&(D.charEdgeStyle=w.charEdgeStyle);w.charEdgeStyleOverride!=null&&(D.charEdgeStyleOverride=w.charEdgeStyleOverride);w.color!=null&&(D.color=w.color);w.colorOverride!=null&&(D.colorOverride=w.colorOverride);w.fontFamily!=null&&(D.fontFamily=w.fontFamily);w.fontFamilyOverride!=
null&&(D.fontFamilyOverride=w.fontFamilyOverride);w.fontSizeIncrement!=null&&(D.fontSizeIncrement=w.fontSizeIncrement);w.fontSizeIncrementOverride!=null&&(D.fontSizeIncrementOverride=w.fontSizeIncrementOverride);w.fontStyle!=null&&(D.fontStyle=w.fontStyle);w.fontStyleOverride!=null&&(D.fontStyleOverride=w.fontStyleOverride);w.textOpacity!=null&&(D.textOpacity=w.textOpacity);w.textOpacityOverride!=null&&(D.textOpacityOverride=w.textOpacityOverride);w.windowColor!=null&&(D.windowColor=w.windowColor);
w.windowColorOverride!=null&&(D.windowColorOverride=w.windowColorOverride);w.windowOpacity!=null&&(D.windowOpacity=w.windowOpacity);w.windowOpacityOverride!=null&&(D.windowOpacityOverride=w.windowOpacityOverride);return D}RL(D,w){var Q={};Object.assign(Q,f3());Object.assign(Q,D);cl(this,Q,w);g.fA(this.player,"captionssettingschanged")}lK(){!this.j&&this.loaded&&(g.oA(this.g$,function(D,w){D.dispose();delete this.g$[w]},this),this.Am())}oK(D,w){switch(D){case "fontSize":if(isNaN(w))break;
D=g.iP(w,-2,4);this.RL({fontSizeIncrement:D});return D;case "reload":w&&!this.j&&ke(this,this.S,!0);break;case "stickyLoading":w!==void 0&&this.U.aN&&(this.U.A("enable_player_captions_persistence_state_machine")?L3(this,!(!w||!w.userInitiated)):g.Jb(this.U)?zO(this,!!w):sR(this,!!w));break;case "track":return NqA(this,w);case "tracklist":return this.Y?g.EU(g.IU(this.Y.Y,!(!w||!w.includeAsr)),Q=>g.V0(Q)):[];
case "translationLanguages":return this.Y?this.Y.O.map(Q=>Object.assign({},Q)):[];
case "sampleSubtitles":this.j||w===void 0||hX(this,!!w);break;case "sampleSubtitlesCustomized":this.j||hX(this,!!w,w);break;case "recommendedTranslationLanguages":return g.Q0();case "defaultTranslationSourceTrackIndices":return this.Y?this.Y.g$:[]}}getOptions(){var D="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.U.aN&&D.push("stickyLoading");return D}z7(){var D=this.S;if(this.L.TY("captions")){if(this.U.A("html5_modify_caption_vss_logging"))return(D=this.videoData.oH??
null)?{cc:g.ytx(D)}:{};if(D){let w=D.vssId;D.translationLanguage&&w&&(w=`t${w}.${g.Sb(D)}`);return{cc:w}}}return{}}p6(D){this.isSubtitlesOn()?(this.U.A("enable_player_captions_persistence_state_machine")&&D?L3(this,!1):g.Jb(this.U)?zO(this,!1):sR(this,!1),AX(this),ke(this,null,!0)):this.hU(D)}hU(D){var w=Hl(this)||!this.S?jj(this,!0):this.S;w&&this.LY(w.vssId,"m");this.isSubtitlesOn()||ke(this,w,this.U.A("enable_player_captions_persistence_state_machine")?D:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.S&&!Hl(this)}V2(){var D=Hl(this);b4(this,D)?ke(this,this.getAudioTrack().Y,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Ch()&&(this.N=!1,this.S=null,this.Y&&(this.Y.dispose(),this.Y=null)),this.c9()&&(D?ke(this,jj(this,!1),!1):this.load()))}C5(D){D&&(this.Ta={top:D.top,right:D.right,bottom:D.bottom,left:D.left,width:1-D.left-D.right,height:1-D.top-D.bottom},this.V.element.style.top=`${this.Ta.top*100}%`,this.V.element.style.left=`${this.Ta.left*100}%`,this.V.element.style.width=
`${this.Ta.width*100}%`,this.V.element.style.height=`${this.Ta.height*100}%`,this.V.element.style.position="absolute",D=q7m(this))&&(this.V.element.style.width=`${D.width}px`,this.V.element.style.height=`${D.height}px`)}onVideoDataChange(D,w){D==="newdata"&&(this.videoData=w,this.loaded&&this.unload(),this.N=!1,this.S=null,this.Y&&(this.Y.dispose(),this.Y=null,g.fA(this.player,"captionschanged",{})),this.c9()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}mC(){if(this.U.r$().Y.oN(g.LuP)){if(this.loaded&&
this.unload(),this.yl=this.L.isFullscreen()||this.U.controlsType==="3",this.j=UR(this),this.ma=Jfm(this),this.j||this.ma){var D=this.L.OU();D&&!D.Lt()&&D.N();this.jA()}}else(D=this.L.OU())&&!D.Lt()&&D.N(),this.L.isFullscreen()?(this.j=this.yl=!0,this.loaded&&this.jA()):(this.yl=this.U.controlsType==="3",this.j=UR(this));ke(this,this.S)}Kt(){var D=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;D&&g.vA(this.player,"innertubeCommand",D)}TI(D,w,Q){var Y=
/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,t="";D&&(t=D.vssId,t=t.replace(Y,""));var O="";D&&D.getId()&&(O=D.getId()||"");D&&D.getXtags()&&(D=D.getXtags(),D=D.replace(Y,""),O=O.concat(`;${D}`));this.D==="HLS"&&(O="");this.L.TI(w?t:"",w?O:"",Q)}LY(D,w){D=(D||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");D.length>0&&this.L.LY(D,w)}});})(_yt_player);
